[package]
name = "bench_cpu_intensive"
version = "0.1.0"
description = "A very simple Tauri Application"
edition = "2024"
rust-version = "1.95"

[build-dependencies]
tauri-build = { workspace = true, default-features = true, features = [
  "codegen",
] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tauri = { workspace = true, default-features = true }

[features]
cef = ["tauri/cef"]
wry = ["tauri/wry"]
