[package]
name = "tauri-plugin-sample"
version = "0.1.0"
edition = "2021"
links = "tauri-plugin-sample"

[dependencies]
tauri = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }
