[workspace]
members = [
  "crates/tauri",
  "crates/tauri-runtime",
  "crates/tauri-runtime-wry",
  "crates/tauri-macros",
  "crates/tauri-utils",
  "crates/tauri-build",
  "crates/tauri-codegen",
  "crates/tauri-plugin",
  "crates/tauri-schema-generator",
  "crates/tauri-schema-worker",
  "crates/tauri-cli",
  "crates/tauri-bundler",
  "crates/tauri-macos-sign",
  "crates/tauri-driver",

  # @tauri-apps/cli rust project
  "packages/cli",

  # integration tests
  "crates/tests/restart",
  "crates/tests/acl",

  # bench
  "bench",
  "bench/tests/cpu_intensive/src-tauri",
  "bench/tests/files_transfer/src-tauri",
  "bench/tests/helloworld/src-tauri",

  # examples
  "examples/file-associations/src-tauri",
  "examples/resources/src-tauri",
  "examples/api/src-tauri",
  "examples/api/src-tauri/tauri-plugin-sample",
]
resolver = "2"

[workspace.package]
authors = ["Tauri Programme within The Commons Conservancy"]
homepage = "https://tauri.app/"
repository = "https://github.com/tauri-apps/tauri"
categories = ["gui", "web-programming"]
license = "Apache-2.0 OR MIT"
edition = "2021"
rust-version = "1.77.2"

[workspace.dependencies]
aes-gcm = "0.10"
anyhow = "1"
apple-codesign = "0.27"
axum = { version = "0.7", default-features = false }
base64 = "0.22"
brotli = { version = "7", default-features = false }
cargo_metadata = "0.19"
cargo_toml = "0.21"
chrono = "0.4"
clap = "4"
clap_complete = "4"
colored = "2"
common-path = "1"
console_error_panic_hook = "0.1"
css-color = "0.2"
ctor = "0.2"
ctrlc = "3"
data-url = "0.3"
dialoguer = "0.11"
dirs = "6"
dpi = "0.1"
duct = "0.13"
dunce = "1"
elf = "0.7"
env_logger = "0.11"
flate2 = "1"
futures = "0.3"
futures-util = "0.3"
getrandom = "0.2"
glob = "0.3"
handlebars = "6"
heck = "0.5"
hex = "0.4"
html5ever = "0.26"
http = "1"
http-body-util = "0.1"
http-range = "0.1.5"
hyper = "1"
hyper-util = "0.1"
icns = "0.1"
ico = "0.4"
ignore = "0.4"
image = { version = "0.25", default-features = false }
include_dir = "0.7"
infer = "0.19"
insta = "1"
itertools = "0.13"
json-patch = "3.0"
json5 = "0.4"
jsonrpsee = "0.24"
jsonrpsee-client-transport = "0.24"
jsonrpsee-core = "0.24"
jsonrpsee-ws-client = { version = "0.24", default-features = false }
jsonschema = "0.29"
kuchiki = "0.8"
local-ip-address = "0.6"
log = "0.4.21"
magic_string = "0.3"
memchr = "2"
mime = "0.3"
minisign = "=0.7.3"
napi = { version = "2.16", default-features = false }
napi-build = "2.1"
napi-derive = "2.16"
native-tls = "0.2"
notify = "8"
notify-debouncer-full = "0.5"
once-cell-regex = "0.2"
os_info = "3"
os_pipe = "1"
oxc_allocator = "0.36"
oxc_ast = "0.36"
oxc_parser = "0.36"
oxc_span = "0.36"
p12 = "0.6"
percent-encoding = "2"
phf = "0.11"
pico-args = "0.5"
plist = "1"
png = "0.17"
pretty_assertions = "1"
proc-macro2 = "1"
proptest = "1.6.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
quote = "1"
rand = "0.8"
raw-window-handle = "0.6"
regex = "1"
resvg = "0.44.0"
schemars = "0.8.18"
semver = "1"
serde = "1"
serde-untagged = "0.1"
serde-value = "0.7"
serde_json = "1"
serde_repr = "0.1"
serde_with = "3"
serial_test = "3"
serialize-to-javascript = "=0.1.1"
sha1 = "0.10"
sha2 = "0.10"
shared_child = "1"
specta = { version = "2.0.0-rc.16", default-features = false }
strsim = "0.11"
sublime_fuzzy = "0.7"
syn = "2"
tao = { version = "0.31.0", default-features = false }
tar = "0.4"
tauri = { path = "crates/tauri", default-features = false }
tauri-bundler = { version = "2.2.3", path = "crates/tauri-bundler", default-features = false }
tauri-cli = { path = "crates/tauri-cli", default-features = false }
tauri-codegen = { version = "2.0.4", path = "crates/tauri-codegen", default-features = false }
tauri-macros = { version = "2.0.4", path = "crates/tauri-macros" }
tauri-plugin = { path = "crates/tauri-plugin" }
tauri-plugin-log = "2"
tauri-plugin-sample = { path = "examples/api/src-tauri/tauri-plugin-sample" }
tauri-runtime = { version = "2.3.0", path = "crates/tauri-runtime" }
tauri-runtime-wry = { version = "2.3.0", path = "crates/tauri-runtime-wry" }
tauri-utils-v1 = "1"
tauri-winres = "0.3"
tempfile = "3"
thiserror = "2"
time = "0.3"
tiny_http = "0.11"
tokio = "1"
toml = "0.8"
toml_edit = "0.22"
tower-service = "0.3"
tracing = "0.1"
ureq = { version = "3", default-features = false }
url = "2"
urlpattern = "0.3"
uuid = "1"
walkdir = "2"
which = "7"
worker = "0.5"
worker-macros = "0.5"
wry = { version = "0.48.1", default-features = false }
x509-certificate = "0.23"
zip = { version = "2", default-features = false }

# default to small, optimized workspace release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true

# profiles for tauri-cli
[profile.dev.package.miniz_oxide]
opt-level = 3

[profile.release-size-optimized]
inherits = "release"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

# Temporary patch to schemars to preserve newlines in docstrings for our reference docs schemas
# See https://github.com/GREsau/schemars/issues/120 for reference
[patch.crates-io]
schemars_derive = { git = 'https://github.com/tauri-apps/schemars.git', branch = 'feat/preserve-description-newlines' }
tauri = { path = "./crates/tauri" }
