packages:
  - packages/api
  - packages/cli
  - crates/tauri-schema-worker
  - examples/api
  - examples/resources
  - examples/file-associations

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

overrides:
  esbuild@>=0.27.3 <0.28.1: '>=0.28.1'
  ws@>=8.0.0 <8.20.1: '>=8.20.1'
