[package]
name = "tauri-cli"
version = "2.2.7"
authors = ["Tauri Programme within The Commons Conservancy"]
edition = "2021"
rust-version = "1.77.2"
categories = ["gui", "web-programming"]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.app"
repository = "https://github.com/tauri-apps/tauri"
description = "Command line interface for building Tauri apps"
include = [
  "src/",
  "/templates",
  "scripts/",
  "*.json",
  "*.rs",
  "tauri.gitignore",
  "tauri-dev-watcher.gitignore",
  "LICENSE*",
]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/tauri-cli-v{ version }/cargo-tauri-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[package.metadata.binstall.overrides.x86_64-apple-darwin]
pkg-fmt = "zip"

[[bin]]
name = "cargo-tauri"
path = "src/main.rs"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\", target_os = \"windows\", target_os = \"macos\"))".dependencies]
cargo-mobile2 = { version = "0.17", default-features = false }

[dependencies]
jsonrpsee = { workspace = true, features = ["server"] }
jsonrpsee-core = { workspace = true }
jsonrpsee-client-transport = { workspace = true, features = ["ws"] }
jsonrpsee-ws-client = { workspace = true }
sublime_fuzzy = { workspace = true }
clap_complete = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
anyhow = { workspace = true }
tauri-bundler = { workspace = true }
colored = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
notify = { workspace = true }
notify-debouncer-full = { workspace = true }
shared_child = { workspace = true }
duct = { workspace = true }
toml_edit = { workspace = true, features = ["serde"] }
json-patch = { workspace = true }
tauri-utils = { version = "2.1.1", path = "../tauri-utils", features = [
  "isolation",
  "schema",
  "config-json5",
  "config-toml",
] }
tauri-utils-v1 = { version = "1", package = "tauri-utils", features = [
  "isolation",
  "schema",
  "config-json5",
  "config-toml",
] }
toml = { workspace = true }
jsonschema = { workspace = true }
handlebars = { workspace = true }
include_dir = { workspace = true }
minisign = { workspace = true }
base64 = { workspace = true }
ureq = { workspace = true, features = ["gzip"] }
os_info = { workspace = true }
semver = { workspace = true }
regex = { workspace = true }
heck = { workspace = true }
dialoguer = { workspace = true }
url = { workspace = true, features = ["serde"] }
os_pipe = { workspace = true }
ignore = { workspace = true }
ctrlc = { workspace = true }
log = { workspace = true, features = ["kv", "kv_std"] }
env_logger = { workspace = true }
icns = { package = "tauri-icns", version = "0.1" }
image = { workspace = true, features = ["ico"] }
axum = { workspace = true, features = ["ws"] }
html5ever = { workspace = true }
kuchiki = { package = "kuchikiki", version = "0.8" }
tokio = { workspace = true, features = ["macros", "sync"] }
common-path = { workspace = true }
serde-value = { workspace = true }
itertools = { workspace = true }
local-ip-address = { workspace = true }
css-color = { workspace = true }
resvg = { workspace = true }
dunce = { workspace = true }
glob = { workspace = true }
# 0.39 raised msrv to above 1.78 but 0.37+ can't compile on 1.77.2 either.
oxc_parser = { workspace = true }
oxc_span = { workspace = true }
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
magic_string = { workspace = true }
phf = { workspace = true, features = ["macros"] }
walkdir = { workspace = true }
elf = { workspace = true }
memchr = { workspace = true }
tempfile = { workspace = true }
uuid = { workspace = true, features = ["v5"] }
rand = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
pretty_assertions = { workspace = true }

[target."cfg(windows)".dependencies.windows-sys]
version = "0.59"
features = [
  "Win32_Storage_FileSystem",
  "Win32_System_IO",
  "Win32_System_Console",
]

[target."cfg(unix)".dependencies]
libc = "0.2"

[target."cfg(target_os = \"macos\")".dependencies]
plist = "1"
tauri-macos-sign = { version = "2.0.1", path = "../tauri-macos-sign" }
object = { version = "0.36", default-features = false, features = [
  "macho",
  "read_core",
  "std",
] }
ar = "0.9"

[features]
default = ["rustls"]
native-tls = [
  "tauri-bundler/native-tls",
  "cargo-mobile2/native-tls",
  "ureq/native-tls",
]
native-tls-vendored = ["native-tls", "tauri-bundler/native-tls-vendored"]
rustls = ["tauri-bundler/rustls", "cargo-mobile2/rustls", "ureq/rustls"]
