#!/usr/bin/env node
// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// Renders every language binding artifact from crates/tauri-ffi/api-manifest.json:
//
//   bindings/c/tauri_ffi.h              C header (prototypes + error codes + docs)
//   bindings/node/src/ffi-decls.js      koffi declarations + error codes
//   bindings/deno/symbols.ts            Deno.dlopen symbol map (blocking -> nonblocking)
//   bindings/python/tauri_ffi_cdef.py   cffi ABI-mode cdef + error codes
//
// Also cross-checks the manifest against the `extern "C"` functions actually
// implemented in crates/tauri-ffi/src/lib.rs, so the two cannot drift.
//
// Usage: node bindings/bindgen/generate.mjs [--check]
//   --check  verify committed outputs are up to date (CI); writes nothing.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const manifestPath = 'crates/tauri-ffi/api-manifest.json'
const manifest = JSON.parse(readFileSync(path.join(repoRoot, manifestPath), 'utf8'))
const checkMode = process.argv.includes('--check')

const BANNER = `Generated by bindings/bindgen/generate.mjs from ${manifestPath} — do not edit.`

// ---------------------------------------------------------------------------
// drift guard: manifest <-> Rust implementation

const srcDir = path.join(repoRoot, 'crates/tauri-ffi/src')
const rustSource = readdirSync(srcDir)
  .filter((f) => f.endsWith('.rs'))
  .map((f) => readFileSync(path.join(srcDir, f), 'utf8'))
  .join('\n')
const implemented = new Set(
  [...rustSource.matchAll(/extern "C" fn (tauri_\w+)/g)].map((m) => m[1])
)
// Also recognize functions produced by the winsupport ffi_* codegen macros
// (getter/setter/action shims for bare Window and Webview), which the plain
// `extern "C" fn` scan cannot see because they are macro-expanded. `\s*` because
// rustfmt breaks the longer invocations onto their own lines.
for (const m of rustSource.matchAll(
  /ffi_(?:getter_bool|setter_bool|action|getter_string)!\(\s*(tauri_\w+)/g
)) {
  implemented.add(m[1])
}
const declared = new Set(manifest.functions.map((f) => f.name))
const missing = [...implemented].filter((name) => !declared.has(name))
const extra = [...declared].filter((name) => !implemented.has(name))
if (missing.length || extra.length) {
  if (missing.length) console.error(`in lib.rs but not in the manifest: ${missing.join(', ')}`)
  if (extra.length) console.error(`in the manifest but not in lib.rs: ${extra.join(', ')}`)
  process.exit(1)
}

// ---------------------------------------------------------------------------
// type tables

const C_PARAM = {
  handle: 'uint64_t',
  str: 'const char *',
  owned_str: 'char *',
  bytes: 'const uint8_t *', // borrowed byte buffer; may be NULL where documented
  bool: 'bool',
  u32: 'uint32_t',
  i32: 'int32_t',
  f64: 'double',
  out_handle: 'uint64_t *',
  out_bool: 'bool *',
  out_u32: 'uint32_t *',
  out_u64: 'uint64_t *',
  out_i32: 'int32_t *',
  out_f64: 'double *',
  out_owned_str: 'char **'
}
const C_RESULT = { status: 'int32_t', u32: 'uint32_t', borrowed_str: 'const char *', void: 'void' }

// koffi accepts C-ish declaration strings; _Out_ marks output params.
const KOFFI_PARAM = {
  ...C_PARAM,
  owned_str: 'void *', // keep the raw pointer so it can be passed back to tauri_string_free
  out_handle: '_Out_ uint64_t *',
  out_bool: '_Out_ bool *',
  out_u32: '_Out_ uint32_t *',
  out_u64: '_Out_ uint64_t *',
  out_i32: '_Out_ int32_t *',
  out_f64: '_Out_ double *',
  out_owned_str: '_Out_ void **' // decoded + freed manually (see ffi.js takeString)
}

const DENO_PARAM = {
  handle: 'u64',
  str: 'buffer', // null-terminated Uint8Array
  owned_str: 'pointer',
  bytes: 'buffer', // raw Uint8Array (or null where documented)
  bool: 'bool',
  u32: 'u32',
  i32: 'i32',
  f64: 'f64',
  out_handle: 'buffer',
  out_bool: 'buffer',
  out_u32: 'buffer',
  out_u64: 'buffer',
  out_i32: 'buffer',
  out_f64: 'buffer',
  out_owned_str: 'buffer'
}
const DENO_RESULT = { status: 'i32', u32: 'u32', borrowed_str: 'pointer', void: 'void' }

/** tauri_app_builder_new -> appBuilderNew */
const alias = (name) =>
  name.replace(/^tauri_/, '').replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase())

/** ERR_INVALID_ARG -> INVALID_ARG (JS/Python code maps) */
const codeKey = (name) => (name === 'OK' ? 'OK' : name.replace(/^ERR_/, ''))

const cPrototype = (fn) => {
  const params = fn.params.map((p) => `${C_PARAM[p.type]}${C_PARAM[p.type].endsWith('*') ? '' : ' '}${p.name}`)
  return `${C_RESULT[fn.result]} ${fn.name}(${params.length ? params.join(', ') : 'void'});`
}

const wrap = (text, width, prefix) => {
  const words = text.split(' ')
  const lines = []
  let line = ''
  for (const word of words) {
    if (line && (line + ' ' + word).length > width) {
      lines.push(line)
      line = word
    } else {
      line = line ? `${line} ${word}` : word
    }
  }
  if (line) lines.push(line)
  return lines.map((l) => `${prefix}${l}`).join('\n')
}

const PLATFORM_NAMES = { macos: 'macOS', windows: 'Windows', linux: 'Linux' }

const contractNote = (fn) => {
  const notes = []
  if (fn.platforms) {
    const names = fn.platforms.map((p) => PLATFORM_NAMES[p] ?? p).join(', ')
    notes.push(`Platform-specific: ${names} only — the symbol exists everywhere but returns TAURI_ERR_UNSUPPORTED on other platforms.`)
  }
  if (fn.thread === 'main') notes.push('Thread: same thread as tauri_app_build (process main thread on macOS).')
  if (fn.blocking) notes.push('Blocks the calling thread.')
  return notes.join(' ')
}

// ---------------------------------------------------------------------------
// C header

function renderHeader() {
  const defines = manifest.errors
    .map((e) => `#define TAURI_${e.name} ${e.value} /* ${e.doc} */`)
    .join('\n')

  const protos = manifest.functions
    .map((fn) => {
      const doc = [fn.doc, contractNote(fn)].filter(Boolean).join(' ')
      return `/*\n${wrap(doc, 76, ' * ')}\n */\n${cPrototype(fn)}`
    })
    .join('\n\n')

  return `/* Copyright 2019-2024 Tauri Programme within The Commons Conservancy
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-License-Identifier: MIT
 *
 * ${BANNER}
 *
 * Experimental C ABI for embedding Tauri (see /ffi-bindings-plan.md).
 *
 * Conventions
 *   - Fallible functions return int32_t: TAURI_OK (0) or a negative error
 *     code. Details via tauri_last_error_message().
 *   - Objects are opaque uint64_t handles; 0 is never a valid handle.
 *   - Structured data crosses the boundary as UTF-8 JSON strings.
 *   - Strings returned through char** out params are owned by the caller;
 *     release them with tauri_string_free().
 *
 * Threading
 *   - tauri_app_build() and tauri_app_run() must be called on the same
 *     thread — the process main thread on macOS. tauri_app_run() blocks
 *     until the app exits. Every other function may be called from any
 *     thread; consume the event queue with tauri_events_next() from a
 *     second thread.
 */

#ifndef TAURI_FFI_H
#define TAURI_FFI_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TAURI_FFI_ABI_VERSION ${manifest.abiVersion}

${defines}

${protos}

#ifdef __cplusplus
}
#endif

#endif /* TAURI_FFI_H */
`
}

// ---------------------------------------------------------------------------
// koffi declarations (Node)

function renderKoffi() {
  const codes = manifest.errors.map((e) => `  ${codeKey(e.name)}: ${e.value}`).join(',\n')
  const decls = manifest.functions
    .map((fn) => {
      const params = fn.params
        .map((p) => `${KOFFI_PARAM[p.type]}${KOFFI_PARAM[p.type].endsWith('*') ? '' : ' '}${p.name}`)
        .join(', ')
      return `  ${alias(fn.name)}: '${C_RESULT[fn.result]} ${fn.name}(${params})'`
    })
    .join(',\n')

  return `// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// ${BANNER}

export const ABI_VERSION = ${manifest.abiVersion}

export const CODES = {
${codes}
}

export const DECLS = {
${decls}
}

/** Binds every declaration against a koffi library handle. */
export function declare(lib) {
  return Object.fromEntries(Object.entries(DECLS).map(([name, decl]) => [name, lib.func(decl)]))
}
`
}

// ---------------------------------------------------------------------------
// Deno.dlopen symbols

function renderDeno() {
  const codes = manifest.errors.map((e) => `  ${codeKey(e.name)}: ${e.value}`).join(',\n')
  const symbols = manifest.functions
    .map((fn) => {
      const params = fn.params.map((p) => `'${DENO_PARAM[p.type]}'`).join(', ')
      // Blocking calls run on Deno's blocking pool and resolve promises —
      // except main-thread-bound ones (tauri_app_run), which must actually
      // block the calling (OS main) thread.
      const nonblocking = fn.blocking && fn.thread !== 'main' ? ', nonblocking: true' : ''
      return `  ${fn.name}: { parameters: [${params}], result: '${DENO_RESULT[fn.result]}'${nonblocking} }`
    })
    .join(',\n')

  return `// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// ${BANNER}
// 'buffer' string params expect null-terminated Uint8Arrays
// (new TextEncoder().encode(s + '\\0')). Blocking calls are declared
// nonblocking so they run off Deno's main thread and resolve promises.

export const ABI_VERSION = ${manifest.abiVersion}

export const CODES = {
${codes}
} as const

// Plain \`as const\` (no \`satisfies\`) so JSR's no-slow-types check accepts it;
// Deno.dlopen validates the interface shape at load time anyway.
export const SYMBOLS = {
${symbols}
} as const
`
}

// ---------------------------------------------------------------------------
// Python cffi cdef

function renderPython() {
  const codes = manifest.errors.map((e) => `    "${codeKey(e.name)}": ${e.value}`).join(',\n')
  const protos = manifest.functions.map(cPrototype).join('\n')

  return `# Copyright 2019-2024 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

# ${BANNER}
# Usage (cffi ABI mode, no compiler needed):
#   from cffi import FFI
#   ffi = FFI(); ffi.cdef(CDEF); lib = ffi.dlopen(path_to_tauri_ffi)

ABI_VERSION = ${manifest.abiVersion}

CODES = {
${codes},
}

CDEF = """
${protos}
"""
`
}

// ---------------------------------------------------------------------------
// write / check

const outputs = {
  'bindings/c/tauri_ffi.h': renderHeader(),
  'bindings/node/src/ffi-decls.js': renderKoffi(),
  'bindings/deno/symbols.ts': renderDeno(),
  'bindings/python/tauri_ffi/_cdef.py': renderPython()
}

let stale = 0
for (const [relative, content] of Object.entries(outputs)) {
  const file = path.join(repoRoot, relative)
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null
  if (current === content) continue
  if (checkMode) {
    console.error(`stale: ${relative} (re-run \`node bindings/bindgen/generate.mjs\`)`)
    stale++
  } else {
    mkdirSync(path.dirname(file), { recursive: true })
    writeFileSync(file, content)
    console.log(`wrote ${relative}`)
  }
}

if (checkMode && stale) process.exit(1)
if (checkMode) console.log('bindings are up to date')
