[package]
name = "tauri-runtime-cef"
version = "0.1.0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64 = "0.22"
cef = { version = "=148.4.0", features = ["build-util"] }
dirs = "6"
dioxus-debug-cell = "0.1"
http = "1"
kuchiki = { package = "kuchikiki", version = "0.8.8-speedreader" }
html5ever = "0.29"
log = "0.4.21"
raw-window-handle = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tauri-runtime = { version = "2.11.2", path = "../tauri-runtime" }
tauri-utils = { version = "2.9.2", path = "../tauri-utils", features = [
  "html-manipulation",
] }
url = "2"
winit = "0.31.0-beta.2"

[target."cfg(windows)".dependencies]
windows = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }

[target."cfg(target_os = \"macos\")".dependencies]
objc2 = "0.6"
objc2-app-kit = { version = "0.3", default-features = false, features = [
  "NSApplication",
  "NSEvent",
  "NSResponder",
  "NSView",
] }
objc2-foundation = { version = "0.3", default-features = false, features = [
  "NSObject",
  "NSRunLoop",
  "NSThread",
  "NSTimer",
] }

[features]
default = ["sandbox"]
devtools = []
macos-private-api = ["tauri-runtime/macos-private-api"]
sandbox = ["cef/sandbox"]
