// Copyright 2019-2021 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

use proc_macro2::Ident;

mod handler;
mod wrapper;

pub use self::{
  handler::Handler,
  wrapper::{Wrapper, WrapperBody},
};

/// The autogenerated wrapper ident
fn format_command_wrapper(function: &Ident) -> Ident {
  quote::format_ident!("__cmd__{}", function)
}
