[package]
name = "tauri-utils"
version = "2.1.1"
description = "Utilities for Tauri"
exclude = ["CHANGELOG.md", "/target"]
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
phf = { workspace = true, features = ["macros"] }
brotli = { workspace = true, features = ["std"], optional = true }
url = { workspace = true, features = ["serde"] }
html5ever = { workspace = true }
kuchiki = { package = "kuchikiki", version = "0.8" }
proc-macro2 = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
# Our code requires at least 0.8.18 so don't change this to 0.8
schemars = { workspace = true, features = ["url", "uuid1"], optional = true }
serde_with = { workspace = true }
aes-gcm = { workspace = true, optional = true }
getrandom = { workspace = true, features = ["std"], optional = true }
serialize-to-javascript = { workspace = true, optional = true }
ctor = { workspace = true }
json5 = { workspace = true, optional = true }
toml = { workspace = true, features = ["parse"] }
json-patch = { workspace = true }
glob = { workspace = true }
urlpattern = { workspace = true }
regex = { workspace = true }
walkdir = { workspace = true, optional = true }
memchr = { workspace = true }
semver = { workspace = true }
infer = { workspace = true }
dunce = { workspace = true }
log = { workspace = true }
cargo_metadata = { workspace = true, optional = true }
serde-untagged = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
http = { workspace = true }

[target."cfg(target_os = \"macos\")".dependencies]
swift-rs = { version = "1", optional = true, features = ["build"] }

[dev-dependencies]
getrandom = { workspace = true, features = ["std"] }
serial_test = { workspace = true }

[features]
build = ["proc-macro2", "quote", "cargo_metadata", "schema", "swift-rs"]
compression = ["brotli"]
schema = ["schemars"]
isolation = ["aes-gcm", "getrandom", "serialize-to-javascript"]
process-relaunch-dangerous-allow-symlink-macos = []
config-json5 = ["json5"]
config-toml = []
resources = ["walkdir"]
