[package]
name = "tauri-schema-generator"
version = "0.0.0"
edition = "2021"
publish = false

[build-dependencies]
tauri-utils = { features = ["schema"], path = "../tauri-utils" }
schemars = { workspace = true, features = ["url", "preserve_order"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true, features = ["serde"] }
