[package]
name = "tauri"
version = "2.2.5"
description = "Make tiny, secure apps for all desktop platforms with Tauri"
exclude = ["/test", "/.scripts", "CHANGELOG.md", "/target"]
readme = "README.md"
links = "Tauri"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
no-default-features = true
features = [
  "wry",
  "unstable",
  "custom-protocol",
  "tray-icon",
  "devtools",
  "image-png",
  "protocol-asset",
  "test",
  "specta",
]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]
default-target = "x86_64-unknown-linux-gnu"
targets = [
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-linux-android",
  "x86_64-apple-ios",
]

[package.metadata.cargo-udeps.ignore]
normal = ["reqwest"]
build = ["tauri-build"]
development = ["quickcheck_macros"]

[dependencies]
serde_json = { workspace = true, features = ["raw_value"] }
serde = { workspace = true, features = ["derive", "rc"] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "sync", "fs", "io-util"] }
futures-util = { workspace = true }
uuid = { workspace = true, features = ["v4"], optional = true }
url = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tauri-runtime = { workspace = true }
tauri-macros = { workspace = true }
tauri-utils = { version = "2.1.1", features = [
  "resources",
], path = "../tauri-utils" }
tauri-runtime-wry = { workspace = true, optional = true }
getrandom = { workspace = true }
serde_repr = { workspace = true }
http = { workspace = true }
dirs = { workspace = true }
percent-encoding = { workspace = true }
raw-window-handle = { workspace = true, features = ["std"] }
glob = { workspace = true }
urlpattern = { workspace = true }
mime = { workspace = true }
data-url = { workspace = true, optional = true }
serialize-to-javascript = { workspace = true }
image = { workspace = true, optional = true }
http-range = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
heck = { workspace = true }
log = { workspace = true }
dunce = { workspace = true }
specta = { workspace = true, features = ["function", "derive"], optional = true }

# desktop
[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd", target_os = "windows", target_os = "macos"))'.dependencies]
muda = { version = "0.15", default-features = false, features = ["serde"] }
tray-icon = { version = "0.19", default-features = false, features = [
  "serde",
], optional = true }

# linux
[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
gtk = { version = "0.18", features = ["v3_24"] }
webkit2gtk = { version = "=2.0.1", features = ["v2_40"] }

# macOS
[target.'cfg(target_os = "macos")'.dependencies]
embed_plist = "1.2"
plist = "1"
objc2 = "0.5"
objc2-foundation = { version = "0.2", default-features = false, features = [
  "std",
  "NSData",
  "NSThread",
] }
objc2-app-kit = { version = "0.2", default-features = false, features = [
  "std",
  "NSApplication",
  "NSColor",
  "NSResponder",
  "NSView",
  "NSWindow",
  "NSImage",
] }
window-vibrancy = "0.5"

# windows
[target."cfg(windows)".dependencies]
webview2-com = "0.34"
window-vibrancy = "0.5"
windows = { version = "0.58", features = ["Win32_Foundation"] }

# mobile
[target.'cfg(any(target_os = "android", all(target_vendor = "apple", not(target_os = "macos"))))'.dependencies]
bytes = { version = "1", features = ["serde"] }
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "stream",
  "rustls-tls",
] }

# android
[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"

# UIKit, i.e. iOS/tvOS/watchOS/visionOS
[target.'cfg(all(target_vendor = "apple", not(target_os = "macos")))'.dependencies]
libc = "0.2"
swift-rs = "1"

[build-dependencies]
glob = { workspace = true }
heck = { workspace = true }
tauri-build = { path = "../tauri-build/", default-features = false, version = "2.0.5" }
tauri-utils = { path = "../tauri-utils/", version = "2.1.1", features = [
  "build",
] }

[dev-dependencies]
proptest = { workspace = true }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tauri = { workspace = true, features = ["wry"] }
tokio = { workspace = true, features = ["full"] }
cargo_toml = { workspace = true }
http-range = { workspace = true }

# macOS
[target.'cfg(target_os = "macos")'.dev-dependencies]
objc2-web-kit = { version = "0.2", features = [
  "objc2-app-kit",
  "WKWebView",
  "WKUserContentController",
] }

[features]
default = ["wry", "compression", "objc-exception", "common-controls-v6"]
unstable = ["tauri-runtime-wry/unstable"]
common-controls-v6 = [
  "tray-icon?/common-controls-v6",
  "muda/common-controls-v6",
]
tray-icon = ["dep:tray-icon"]
tracing = ["dep:tracing", "tauri-macros/tracing", "tauri-runtime-wry/tracing"]
test = []
compression = ["tauri-macros/compression", "tauri-utils/compression"]
wry = ["tauri-runtime-wry"]
objc-exception = ["tauri-runtime-wry/objc-exception"]
linux-libxdo = ["tray-icon/libxdo", "muda/libxdo"]
isolation = ["tauri-utils/isolation", "tauri-macros/isolation", "uuid"]
custom-protocol = ["tauri-macros/custom-protocol"]
# TODO: Remove these flags in v3 and/or enable them by default behind a mobile flag https://github.com/tauri-apps/tauri/issues/12384
# For now those feature flags keep enabling reqwest features in case some users depend on that by accident.
native-tls = ["reqwest/native-tls"]
native-tls-vendored = ["reqwest/native-tls-vendored"]
rustls-tls = []
devtools = ["tauri-runtime/devtools", "tauri-runtime-wry/devtools"]
process-relaunch-dangerous-allow-symlink-macos = [
  "tauri-utils/process-relaunch-dangerous-allow-symlink-macos",
]
macos-private-api = [
  "tauri-runtime/macos-private-api",
  "tauri-runtime-wry/macos-private-api",
]
webview-data-url = ["data-url"]
protocol-asset = ["http-range"]
config-json5 = ["tauri-macros/config-json5"]
config-toml = ["tauri-macros/config-toml"]
image-ico = ["image/ico"]
image-png = ["image/png"]
macos-proxy = ["tauri-runtime-wry/macos-proxy"]
specta = ["dep:specta"]

[[example]]
name = "commands"
path = "../../examples/commands/main.rs"

[[example]]
name = "helloworld"
path = "../../examples/helloworld/main.rs"

[[example]]
name = "multiwebview"
path = "../../examples/multiwebview/main.rs"
required-features = ["unstable"]

[[example]]
name = "multiwindow"
path = "../../examples/multiwindow/main.rs"

[[example]]
name = "run-iteration"
path = "../../examples/run-iteration/main.rs"

[[example]]
name = "splashscreen"
path = "../../examples/splashscreen/main.rs"

[[example]]
name = "state"
path = "../../examples/state/main.rs"

[[example]]
name = "streaming"
path = "../../examples/streaming/main.rs"

[[example]]
name = "isolation"
path = "../../examples/isolation/main.rs"
required-features = ["isolation"]
