[package]
name = "tauri-macos-sign"
version = "2.0.1"
authors = ["Tauri Programme within The Commons Conservancy"]
license = "Apache-2.0 OR MIT"
keywords = ["codesign", "signing", "macos", "ios", "tauri"]
repository = "https://github.com/tauri-apps/tauri"
description = "Code signing utilities for macOS and iOS apps"
edition = "2021"
rust-version = "1.77.2"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
x509-certificate = { workspace = true }
once-cell-regex = { workspace = true }
os_pipe = { workspace = true }
plist = { workspace = true }
rand = { workspace = true }
dirs = { workspace = true }
log = { workspace = true, features = ["kv"] }
apple-codesign = { workspace = true }
chrono = { workspace = true }
p12 = { workspace = true }
