[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.90"
license = "Apache-2.0 OR MIT"

[lib]
name = "api_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { path = "../../../crates/tauri-build", features = [
  "codegen",
  "isolation",
] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
log = "0.4.21"
tauri-plugin-sample = { path = "./tauri-plugin-sample/" }

[target.'cfg(not(target_env = "ohos"))'.dependencies]
tauri-plugin-log = "2"

[target.'cfg(target_env = "ohos")'.dependencies]
napi-ohos = { version = "1.1" }
napi-derive-ohos = { version = "1.1" }

[dependencies.tauri]
path = "../../../crates/tauri"
features = [
  "protocol-asset",
  "image-ico",
  "image-png",
  "isolation",
  "macos-private-api",
  "tray-icon",
]

[dev-dependencies.tauri]
path = "../../../crates/tauri"
features = ["test"]

[features]
prod = ["tauri/custom-protocol"]
