[package]
name = "cef-offscreen"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tauri = { workspace = true }
tauri-runtime-cef = { workspace = true }
vello = "0.10"
pollster = "0.4"

[build-dependencies]
tauri-build = { workspace = true }

[features]
custom-protocol = ["tauri/custom-protocol"]
