[package]
name = "tauri-codegen"
version = "2.0.4"
description = "code generation meant to be consumed inside of `tauri` through `tauri-build` or `tauri-macros`"
exclude = ["CHANGELOG.md", "/target"]
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
sha2 = { workspace = true }
base64 = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tauri-utils = { version = "2.1.1", path = "../tauri-utils", features = [
  "build",
] }
thiserror = { workspace = true }
walkdir = { workspace = true }
brotli = { workspace = true, features = ["std"], optional = true }
regex = { workspace = true, optional = true }
uuid = { workspace = true, features = ["v4"] }
semver = { workspace = true }
ico = { workspace = true }
png = { workspace = true }
json-patch = { workspace = true }
url = { workspace = true }

[target."cfg(target_os = \"macos\")".dependencies]
plist = "1"
time = { version = "0.3", features = ["parsing", "formatting"] }

[features]
compression = ["brotli", "tauri-utils/compression"]
isolation = ["tauri-utils/isolation"]
config-json5 = ["tauri-utils/config-json5"]
config-toml = ["tauri-utils/config-toml"]
