// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// The structure of a FreeBSD pkg package looks something like this:
//
// foobar-1.2.3.pkg             # txz archive produced by `pkg create`
//     +COMPACT_MANIFEST            # Compact package metadata generated by pkg
//     +MANIFEST                    # UCL package metadata
//     +PRE_INSTALL                 # Pre-installation script (optional)
//     +POST_INSTALL                # Post-installation script (optional)
//     +PRE_DEINSTALL               # Pre-uninstallation script (optional)
//     +POST_DEINSTALL              # Post-uninstallation script (optional)
//     usr/local/bin/foobar                         # Binary executable file
//     usr/local/share/applications/foobar.desktop  # Desktop file (for apps)
//     usr/local/share/icons/hicolor/...            # Icon files (for apps)
//     usr/local/share/metainfo/foobar.metainfo.xml # AppStream metadata (optional)
//     usr/local/lib/foobar/...                     # Other resource files
//
// `pkg create` takes a staged root directory, a plist describing installed
// files, and a metadata directory. We stage application files under the FreeBSD
// local prefix (/usr/local), generate freedesktop metadata from the bundle
// configuration, write +MANIFEST in UCL format, copy lifecycle scripts into the
// metadata directory, then let `pkg create` assemble the final .pkg archive.

use super::freedesktop;
use crate::{
  bundle::settings::Arch,
  error::{Context, ErrorExt},
  utils::{fs_utils, CommandExt},
  Settings,
};
use std::{
  fs::{self, File, OpenOptions},
  io::Write,
  os::unix::fs::{OpenOptionsExt, PermissionsExt},
  path::{Path, PathBuf},
  process::Command,
};
use walkdir::WalkDir;

const DEFAULT_PORT_CATEGORY: &str = "x11";
const PREFIX: &str = "/usr/local";

/// Bundles the project as a FreeBSD pkg package.
pub fn bundle_project(settings: &Settings) -> crate::Result<Vec<PathBuf>> {
  let arch = freebsd_arch(settings.binary_arch())?;
  let port_name = sanitize_port_name(settings.product_name());
  let package_base_name = format!("{}-{}-{}", port_name, settings.version_string(), arch);
  let base_dir = settings.project_out_directory().join("bundle/pkg");
  let package_dir = base_dir.join(&package_base_name);
  fs_utils::remove_dir_all(&package_dir)?;

  let root_dir = package_dir.join("pkgroot");
  let prefix_dir = root_dir.join(PREFIX.trim_start_matches('/'));
  let metadata_dir = package_dir.join("metadata");
  let plist_path = package_dir.join("pkg-plist");
  let origin = format!(
    "{}/{}",
    settings
      .pkg()
      .category
      .as_deref()
      .unwrap_or(DEFAULT_PORT_CATEGORY),
    port_name
  );

  log::info!(action = "Bundling"; "{} as FreeBSD pkg", settings.product_name());

  generate_stage(settings, &prefix_dir).context("Failed to generate FreeBSD pkg stage")?;
  fs_utils::copy_custom_files(&settings.pkg().files, &prefix_dir)
    .context("Failed to copy custom files")?;
  normalize_pkgroot_permissions(&root_dir)
    .context("Failed to normalize FreeBSD pkg file permissions")?;
  generate_pkg_plist(&plist_path, &prefix_dir).context("Failed to generate pkg plist")?;
  generate_pkg_metadata(settings, &port_name, &origin, &metadata_dir)
    .context("Failed to generate pkg metadata")?;
  generate_scripts(settings, &metadata_dir).context("Failed to create pkg scripts")?;

  fs::create_dir_all(&base_dir).fs_context("failed to create pkg output directory", &base_dir)?;
  let output_path = base_dir.join(format!("{port_name}-{}.pkg", settings.version_string()));
  let _ = fs::remove_file(&output_path);

  let status = Command::new("pkg")
    .args(["create", "-m"])
    .arg(&metadata_dir)
    .args(["-p"])
    .arg(&plist_path)
    .args(["-r"])
    .arg(&root_dir)
    .args(["-o"])
    .arg(&base_dir)
    .piped()
    .map_err(crate::Error::IoError)
    .context("failed to run pkg create")?;

  if !status.success() {
    return Err(crate::Error::GenericError(format!(
      "pkg create failed for {port_name}-{}",
      settings.version_string()
    )));
  }

  if !output_path.exists() {
    return Err(crate::Error::GenericError(format!(
      "pkg create completed but {} was not found",
      output_path.display()
    )));
  }

  Ok(vec![output_path])
}

fn normalize_pkgroot_permissions(root_dir: &Path) -> crate::Result<()> {
  for entry in WalkDir::new(root_dir).into_iter().filter_map(Result::ok) {
    let path = entry.path();
    if entry.file_type().is_dir() {
      fs::set_permissions(path, fs::Permissions::from_mode(0o755))?;
    } else if entry.file_type().is_file() {
      let mode = if path.strip_prefix(root_dir).is_ok_and(|path| {
        path
          .components()
          .any(|component| component.as_os_str() == "bin")
      }) {
        0o755
      } else {
        0o644
      };
      fs::set_permissions(path, fs::Permissions::from_mode(mode))?;
    }
  }
  Ok(())
}

fn generate_stage(settings: &Settings, stage_dir: &Path) -> crate::Result<()> {
  let bin_dir = stage_dir.join("bin");
  for bin in settings.binaries() {
    let bin_path = settings.binary_path(bin);
    let dest = bin_dir.join(bin.name());
    fs_utils::copy_file(&bin_path, &dest)
      .with_context(|| format!("Failed to copy binary from {bin_path:?} to {dest:?}"))?;
  }

  settings
    .copy_binaries(&bin_dir)
    .context("Failed to copy external binaries")?;

  let resource_dir = stage_dir.join("lib").join(settings.product_name());
  settings
    .copy_resources(&resource_dir)
    .context("Failed to copy resource files")?;

  freedesktop::copy_icon_files(settings, stage_dir).context("Failed to copy icon files")?;
  freedesktop::generate_desktop_file(settings, &settings.pkg().desktop_template, stage_dir)
    .context("Failed to create desktop file")?;

  Ok(())
}

fn generate_pkg_metadata(
  settings: &Settings,
  port_name: &str,
  origin: &str,
  metadata_dir: &Path,
) -> crate::Result<()> {
  fs::create_dir_all(metadata_dir).fs_context("failed to create pkg metadata", metadata_dir)?;

  let maintainer = settings
    .authors_comma_separated()
    .filter(|authors| authors.contains('@'))
    .or_else(|| settings.publisher().map(ToString::to_string))
    .filter(|publisher| publisher.contains('@'))
    .unwrap_or_else(|| "ports@FreeBSD.org".into());
  let comment = if settings.short_description().is_empty() {
    settings.product_name().to_string()
  } else {
    settings.short_description().to_string()
  };
  let description = settings
    .long_description()
    .filter(|description| !description.is_empty())
    .unwrap_or_else(|| {
      if settings.short_description().is_empty() {
        settings.product_name()
      } else {
        settings.short_description()
      }
    });
  let (abi, altabi) = pkg_abi()?;

  let mut manifest = fs_utils::create_file(&metadata_dir.join("+MANIFEST"))?;
  writeln!(manifest, "name: \"{}\"", ucl_escape(port_name))?;
  writeln!(
    manifest,
    "version: \"{}\"",
    ucl_escape(settings.version_string())
  )?;
  writeln!(manifest, "origin: \"{}\"", ucl_escape(origin))?;
  writeln!(manifest, "comment: \"{}\"", ucl_escape(&comment))?;
  writeln!(manifest, "maintainer: \"{}\"", ucl_escape(&maintainer))?;
  if let Some(homepage) = settings.homepage_url() {
    writeln!(manifest, "www: \"{}\"", ucl_escape(homepage))?;
  }
  writeln!(manifest, "abi: \"{}\"", ucl_escape(&abi))?;
  writeln!(manifest, "arch: \"{}\"", ucl_escape(&altabi))?;
  writeln!(manifest, "prefix: \"{PREFIX}\"")?;
  writeln!(manifest, "desc: <<EOD")?;
  writeln!(manifest, "{description}")?;
  writeln!(manifest, "EOD")?;
  if let Some((licenses, logic)) = settings.license().as_deref().and_then(freebsd_licenses) {
    writeln!(manifest, "licenselogic: \"{logic}\"")?;
    writeln!(manifest, "licenses: [")?;
    for license in licenses {
      writeln!(manifest, "    \"{}\"", ucl_escape(&license))?;
    }
    writeln!(manifest, "]")?;
  }
  writeln!(manifest, "deps: {{")?;
  for dependency in package_dependencies(settings)? {
    let PackageDependency {
      name,
      origin,
      version,
    } = dependency;
    writeln!(manifest, "    \"{}\": {{", ucl_escape(&name))?;
    writeln!(manifest, "        origin: \"{origin}\"")?;
    writeln!(manifest, "        version: \"{}\"", ucl_escape(&version))?;
    writeln!(manifest, "    }}")?;
  }
  writeln!(manifest, "}}")?;
  write_string_array(
    &mut manifest,
    "categories",
    Some([settings
      .pkg()
      .category
      .as_deref()
      .unwrap_or(DEFAULT_PORT_CATEGORY)]),
  )?;
  write_string_array(
    &mut manifest,
    "provides",
    settings.pkg().provides.as_deref(),
  )?;
  write_string_array(
    &mut manifest,
    "conflicts",
    Some(package_relationships(
      settings.pkg().conflicts.as_deref(),
      "conflict",
    )?),
  )?;
  write_string_array(
    &mut manifest,
    "replaces",
    Some(package_relationships(
      settings.pkg().replaces.as_deref(),
      "replacement",
    )?),
  )?;

  Ok(())
}

fn generate_pkg_plist(path: &Path, stage_dir: &Path) -> crate::Result<()> {
  let mut entries = Vec::new();
  for entry in WalkDir::new(stage_dir).into_iter().filter_map(Result::ok) {
    if entry.file_type().is_file() {
      let rel = entry.path().strip_prefix(stage_dir)?.to_string_lossy();
      entries.push(rel.replace(std::path::MAIN_SEPARATOR, "/"));
    }
  }
  entries.sort();

  let mut file = fs_utils::create_file(path)?;
  for entry in entries {
    writeln!(file, "{entry}")?;
  }
  Ok(())
}

fn freebsd_arch(arch: Arch) -> crate::Result<&'static str> {
  match arch {
    Arch::X86_64 => Ok("amd64"),
    Arch::X86 => Ok("i386"),
    Arch::AArch64 => Ok("arm64"),
    Arch::Armhf => Ok("armv7"),
    Arch::Riscv64 => Ok("riscv64"),
    target => Err(crate::Error::ArchError(format!(
      "Unsupported FreeBSD architecture: {target:?}"
    ))),
  }
}

fn sanitize_port_name(name: &str) -> String {
  let mut sanitized = String::with_capacity(name.len());
  for ch in name.chars().flat_map(char::to_lowercase) {
    if ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '.') {
      sanitized.push(ch);
    } else if !sanitized.ends_with('-') {
      sanitized.push('-');
    }
  }
  sanitized.trim_matches('-').to_string()
}

fn pkg_abi() -> crate::Result<(String, String)> {
  let abi = pkg_config("ABI")?;
  let altabi = pkg_config("ALTABI")?;
  Ok((abi, altabi))
}

fn pkg_config(key: &str) -> crate::Result<String> {
  let output = Command::new("pkg")
    .args(["config", key])
    .output()
    .map_err(crate::Error::IoError)
    .with_context(|| format!("failed to run pkg config {key}"))?;
  if !output.status.success() {
    return Err(crate::Error::GenericError(format!(
      "pkg config {key} failed"
    )));
  }
  Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

struct PackageDependency {
  name: String,
  origin: String,
  version: String,
}

fn package_dependencies(settings: &Settings) -> crate::Result<Vec<PackageDependency>> {
  let mut names = vec![
    "dbus".to_string(),
    "desktop-file-utils".to_string(),
    "gtk3".to_string(),
    "webkit2-gtk_41".to_string(),
  ];
  if let Some(depends) = &settings.pkg().depends {
    names.extend(depends.iter().cloned());
  }
  names.sort();
  names.dedup();
  names
    .into_iter()
    .map(|name| package_dependency(&name))
    .collect()
}

fn package_dependency(name: &str) -> crate::Result<PackageDependency> {
  let output = Command::new("pkg")
    .args(["query", "%n\t%o\t%v", name])
    .output()
    .map_err(crate::Error::IoError)
    .with_context(|| format!("failed to query FreeBSD package {name}"))?;

  if !output.status.success() {
    return Err(crate::Error::GenericError(format!(
      "FreeBSD package dependency {name} is not installed"
    )));
  }

  let stdout = String::from_utf8_lossy(&output.stdout);
  let (name, origin, version) = stdout
    .trim()
    .split_once('\t')
    .and_then(|(name, rest)| {
      rest
        .split_once('\t')
        .map(|(origin, version)| (name, origin, version))
    })
    .ok_or_else(|| {
      crate::Error::GenericError(format!("failed to parse pkg query output for {name}"))
    })?;

  Ok(PackageDependency {
    name: name.to_string(),
    origin: origin.to_string(),
    version: version.to_string(),
  })
}

fn package_relationships(
  patterns: Option<&[String]>,
  relationship: &str,
) -> crate::Result<Vec<String>> {
  let Some(patterns) = patterns else {
    return Ok(Vec::new());
  };

  let mut package_names = Vec::new();
  for pattern in patterns {
    let resolved_names = resolve_package_names(pattern);
    if resolved_names.is_empty() {
      return Err(crate::Error::GenericError(format!(
        "FreeBSD pkg {relationship} `{pattern}` does not match an installed package or a package in the configured repositories. Use a real package name or a pkg query pattern that resolves on the build host."
      )));
    } else {
      package_names.extend(resolved_names);
    }
  }

  package_names.sort();
  package_names.dedup();
  Ok(package_names)
}

fn resolve_package_names(pattern: &str) -> Vec<String> {
  let mut package_names = Vec::new();
  for query_command in ["query", "rquery"] {
    let Ok(output) = Command::new("pkg")
      .args([query_command, "%n", pattern])
      .output()
    else {
      continue;
    };

    if !output.status.success() {
      continue;
    }

    package_names.extend(
      String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(str::trim)
        .filter(|name| !name.is_empty())
        .map(ToString::to_string),
    );
  }
  package_names
}

fn generate_scripts(settings: &Settings, metadata_dir: &Path) -> crate::Result<()> {
  if let Some(script_path) = &settings.pkg().pre_install_script {
    create_script_file_from_path(script_path, &metadata_dir.join("+PRE_INSTALL"))?;
  }
  if let Some(script_path) = &settings.pkg().post_install_script {
    create_script_file_from_path(script_path, &metadata_dir.join("+POST_INSTALL"))?;
  }
  if let Some(script_path) = &settings.pkg().pre_remove_script {
    create_script_file_from_path(script_path, &metadata_dir.join("+PRE_DEINSTALL"))?;
  }
  if let Some(script_path) = &settings.pkg().post_remove_script {
    create_script_file_from_path(script_path, &metadata_dir.join("+POST_DEINSTALL"))?;
  }
  Ok(())
}

fn create_script_file_from_path(from: &Path, to: &Path) -> crate::Result<()> {
  let mut from = File::open(from)?;
  let mut file = OpenOptions::new()
    .create(true)
    .truncate(true)
    .write(true)
    .mode(0o755)
    .open(to)?;
  std::io::copy(&mut from, &mut file)?;
  Ok(())
}

fn write_string_array(
  manifest: &mut impl Write,
  key: &str,
  values: Option<impl IntoIterator<Item = impl AsRef<str>>>,
) -> crate::Result<()> {
  let Some(values) = values else {
    return Ok(());
  };

  let values = values.into_iter().collect::<Vec<_>>();
  if values.is_empty() {
    return Ok(());
  }

  writeln!(manifest, "{key}: [")?;
  for value in values {
    writeln!(manifest, "    \"{}\"", ucl_escape(value.as_ref()))?;
  }
  writeln!(manifest, "]")?;
  Ok(())
}

fn freebsd_licenses(license: &str) -> Option<(Vec<String>, &'static str)> {
  let license = license.trim();
  if license.is_empty() {
    return None;
  }

  let (separator, logic) = if license.contains(" OR ") {
    (" OR ", "or")
  } else if license.contains(" AND ") {
    (" AND ", "and")
  } else {
    (" ", "single")
  };

  let licenses = license
    .split(separator)
    .filter_map(freebsd_license_token)
    .map(ToString::to_string)
    .collect::<Vec<_>>();

  (!licenses.is_empty()).then_some((licenses, logic))
}

fn freebsd_license_token(license: &str) -> Option<&'static str> {
  match license.trim_matches(|c| c == '(' || c == ')').trim() {
    "Apache-2.0" => Some("APACHE20"),
    "BSD-2-Clause" => Some("BSD2CLAUSE"),
    "BSD-3-Clause" => Some("BSD3CLAUSE"),
    "GPL-2.0" | "GPL-2.0-only" => Some("GPLv2"),
    "GPL-3.0" | "GPL-3.0-only" => Some("GPLv3"),
    "LGPL-2.1" | "LGPL-2.1-only" => Some("LGPL21"),
    "LGPL-3.0" | "LGPL-3.0-only" => Some("LGPL3"),
    "MIT" => Some("MIT"),
    "MPL-2.0" => Some("MPL20"),
    _ => None,
  }
}

fn ucl_escape(value: &str) -> String {
  value.replace('\\', "\\\\").replace('"', "\\\"")
}
