/* Copyright 2019-2024 Tauri Programme within The Commons Conservancy
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-License-Identifier: MIT
 *
 * Experimental C ABI for embedding Tauri (M0 spike — see /ffi-bindings-plan.md).
 * Hand-written for now; generated by cbindgen from M1 and from the API
 * manifest from M3.
 *
 * Conventions
 *   - Fallible functions return int32_t: TAURI_OK (0) or a negative error
 *     code. Details via tauri_last_error_message().
 *   - Objects are opaque uint64_t handles; 0 is never a valid handle.
 *   - Structured data crosses the boundary as UTF-8 JSON strings.
 *   - Strings returned through char** out params are owned by the caller;
 *     release them with tauri_string_free().
 *
 * Threading
 *   - tauri_app_build() and tauri_app_run() must be called on the same
 *     thread — the process main thread on macOS. tauri_app_run() blocks
 *     until the app exits.
 *   - Every other function may be called from any thread. Consume the event
 *     queue with tauri_events_next() from a second thread (or from the main
 *     thread before calling run, for early events).
 */

#ifndef TAURI_FFI_H
#define TAURI_FFI_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TAURI_OK 0
#define TAURI_ERR_GENERIC -1
#define TAURI_ERR_INVALID_HANDLE -2
#define TAURI_ERR_TIMEOUT -3
#define TAURI_ERR_CLOSED -4
#define TAURI_ERR_INVALID_ARG -5
#define TAURI_ERR_PANIC -7

/* --- meta ---------------------------------------------------------------- */

/* Semver of the tauri-ffi crate. Borrowed static string, do not free. */
const char *tauri_ffi_version(void);
uint32_t tauri_ffi_abi_version(void);

/* Message for the last error on this thread, or NULL. Borrowed pointer,
 * valid until the next failing call on the same thread. */
const char *tauri_last_error_message(void);

/* Releases a string returned through a char** out param. */
void tauri_string_free(char *str);

/* Drops any handle (builder, app, resolver). */
int32_t tauri_handle_close(uint64_t handle);

/* --- app builder ---------------------------------------------------------- */

/* config_json follows the tauri.conf.json schema (unknown fields rejected). */
int32_t tauri_app_builder_new(const char *config_json, uint64_t *out_builder);

/* Serve `WebviewUrl::App` paths (e.g. "index.html") from this directory. */
int32_t tauri_app_builder_set_assets_dir(uint64_t builder, const char *path);

/* Register a command; its invokes arrive on the event queue as
 * {"type":"invoke","id":<resolver>,"command":...,"payload":...,"webview":...}. */
int32_t tauri_app_builder_register_command(uint64_t builder, const char *name);

/* Capability JSON/TOML string (capability file format). If none is added, a
 * default granting core:default to all windows is applied. */
int32_t tauri_app_builder_add_capability(uint64_t builder, const char *capability);

/* Consumes the builder. Main thread only. Windows declared in the config are
 * created when the app runs. */
int32_t tauri_app_build(uint64_t builder, uint64_t *out_app);

/* --- run loop ------------------------------------------------------------- */

/* Blocks until the app exits; out_exit_code receives the requested exit code.
 * Must be called on the thread that called tauri_app_build. */
int32_t tauri_app_run(uint64_t app, int32_t *out_exit_code);

/* Requests exit from any thread. */
int32_t tauri_app_exit(uint64_t app, int32_t code);

/* --- event queue ----------------------------------------------------------- */

/* Waits up to timeout_ms for the next message. Returns TAURI_OK with an owned
 * JSON string in *out_json (free with tauri_string_free), TAURI_ERR_TIMEOUT,
 * or TAURI_ERR_CLOSED after shutdown. Message types:
 *   {"type":"ready"} | {"type":"exit"} | {"type":"exit-requested","code":N}
 *   {"type":"window-event","label":L,"event":{"kind":...}}
 *   {"type":"event","event":E,"id":N,"payload":...}
 *   {"type":"invoke","id":R,"command":C,"payload":...,"webview":L} */
int32_t tauri_events_next(uint64_t app, uint32_t timeout_ms, char **out_json);

/* --- events ---------------------------------------------------------------- */

int32_t tauri_app_emit(uint64_t app, const char *event, const char *payload_json);
int32_t tauri_app_emit_to(uint64_t app, const char *label, const char *event,
                          const char *payload_json);
int32_t tauri_app_listen(uint64_t app, const char *event, uint32_t *out_listener);
int32_t tauri_app_unlisten(uint64_t app, uint32_t listener);

/* --- webviews --------------------------------------------------------------- */

int32_t tauri_webview_eval(uint64_t app, const char *label, const char *js);

/* --- invoke (commands) ------------------------------------------------------ */

/* Both consume the resolver handle; callable from any thread, any time. */
int32_t tauri_invoke_resolve(uint64_t resolver, const char *json);
int32_t tauri_invoke_reject(uint64_t resolver, const char *json);

#ifdef __cplusplus
}
#endif

#endif /* TAURI_FFI_H */
