/* Copyright 2019-2024 Tauri Programme within The Commons Conservancy
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-License-Identifier: MIT
 *
 * Generated by bindings/bindgen/generate.mjs from crates/tauri-ffi/api-manifest.json — do not edit.
 *
 * Experimental C ABI for embedding Tauri (see /ffi-bindings-plan.md).
 *
 * Conventions
 *   - Fallible functions return int32_t: TAURI_OK (0) or a negative error
 *     code. Details via tauri_last_error_message().
 *   - Objects are opaque uint64_t handles; 0 is never a valid handle.
 *   - Structured data crosses the boundary as UTF-8 JSON strings.
 *   - Strings returned through char** out params are owned by the caller;
 *     release them with tauri_string_free().
 *
 * Threading
 *   - tauri_app_build() and tauri_app_run() must be called on the same
 *     thread — the process main thread on macOS. tauri_app_run() blocks
 *     until the app exits. Every other function may be called from any
 *     thread; consume the event queue with tauri_events_next() from a
 *     second thread.
 */

#ifndef TAURI_FFI_H
#define TAURI_FFI_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TAURI_FFI_ABI_VERSION 2

#define TAURI_OK 0 /* Success. */
#define TAURI_ERR_GENERIC -1 /* Operation failed; details via tauri_last_error_message. */
#define TAURI_ERR_INVALID_HANDLE -2 /* Unknown, closed or wrong-type handle. */
#define TAURI_ERR_TIMEOUT -3 /* tauri_events_next timed out with no message. */
#define TAURI_ERR_CLOSED -4 /* The app has shut down; no more messages. */
#define TAURI_ERR_INVALID_ARG -5 /* Null pointer, invalid UTF-8 or malformed JSON argument. */
#define TAURI_ERR_PANIC -7 /* Rust panic caught at the FFI boundary. */
#define TAURI_ERR_NOT_FOUND -8 /* No object with the requested label/name. */

/*
 * Semver of the tauri-ffi crate. Borrowed static string, do not free.
 */
const char * tauri_ffi_version(void);

/*
 * Monotonic ABI version; bumped on breaking changes.
 */
uint32_t tauri_ffi_abi_version(void);

/*
 * Message for the last error on this thread, or NULL. Borrowed pointer, valid
 * until the next failing call on the same thread.
 */
const char * tauri_last_error_message(void);

/*
 * Releases a string returned through a char** out param.
 */
void tauri_string_free(char *str);

/*
 * Drops any handle (builder, app, window, resolver). Closing a window handle
 * does not affect the window itself.
 */
int32_t tauri_handle_close(uint64_t handle);

/*
 * Creates an app builder from a tauri.conf.json-shaped JSON string (unknown
 * fields rejected).
 */
int32_t tauri_app_builder_new(const char *config_json, uint64_t *out_builder);

/*
 * Serves `WebviewUrl::App` paths (e.g. "index.html") from this directory.
 */
int32_t tauri_app_builder_set_assets_dir(uint64_t builder, const char *path);

/*
 * Registers a command name; its invokes arrive on the event queue as
 * {"type":"invoke","id":<resolver>,"command":...,"payload":...,"webview":...}.
 */
int32_t tauri_app_builder_register_command(uint64_t builder, const char *name);

/*
 * Adds a capability (JSON or TOML string, capability file format). If none is
 * added, a default granting core:default to all windows is applied.
 */
int32_t tauri_app_builder_add_capability(uint64_t builder, const char *capability);

/*
 * Consumes the builder and builds the app. Windows declared in the config are
 * created when the app runs. Thread: same thread as tauri_app_build (process
 * main thread on macOS).
 */
int32_t tauri_app_build(uint64_t builder, uint64_t *out_app);

/*
 * Runs the event loop until the app exits; out_exit_code receives the
 * requested exit code. Must be called on the thread that called
 * tauri_app_build. Run events are also delivered through the event queue.
 * Thread: same thread as tauri_app_build (process main thread on macOS).
 * Blocks the calling thread.
 */
int32_t tauri_app_run(uint64_t app, int32_t *out_exit_code);

/*
 * Requests app exit from any thread.
 */
int32_t tauri_app_exit(uint64_t app, int32_t code);

/*
 * Waits up to timeout_ms for the next queued message (run events, subscribed
 * events, invokes). On OK, *out_json is an owned JSON string — free with
 * tauri_string_free. Returns ERR_TIMEOUT on timeout and ERR_CLOSED after
 * shutdown. Message types: {"type":"ready"} | {"type":"exit"} |
 * {"type":"exit-requested","code":N} |
 * {"type":"window-event","label":L,"event":{"kind":...}} |
 * {"type":"event","event":E,"id":N,"payload":...} |
 * {"type":"invoke","id":R,"command":C,"payload":...,"webview":L} Blocks the
 * calling thread.
 */
int32_t tauri_events_next(uint64_t app, uint32_t timeout_ms, char **out_json);

/*
 * Emits an event to all listeners (Rust, frontend and FFI subscribers).
 * payload_json must be valid JSON.
 */
int32_t tauri_app_emit(uint64_t app, const char *event, const char *payload_json);

/*
 * Emits an event to every target with the given label.
 */
int32_t tauri_app_emit_to(uint64_t app, const char *label, const char *event, const char *payload_json);

/*
 * Subscribes to an event (any target). Deliveries arrive on the event queue as
 * {"type":"event","event":...,"id":...,"payload":...}.
 */
int32_t tauri_app_listen(uint64_t app, const char *event, uint32_t *out_listener);

/*
 * Removes an event subscription.
 */
int32_t tauri_app_unlisten(uint64_t app, uint32_t listener);

/*
 * Resolves a pending invoke with a JSON value. Consumes the resolver handle.
 * Callable from any thread, any time after the invoke was delivered.
 */
int32_t tauri_invoke_resolve(uint64_t resolver, const char *json);

/*
 * Rejects a pending invoke with a JSON value. Consumes the resolver handle.
 */
int32_t tauri_invoke_reject(uint64_t resolver, const char *json);

/*
 * Creates a webview window from a WindowConfig JSON object (same shape as
 * entries of app.windows in tauri.conf.json). Blocks until the running event
 * loop has created the window — call only while the app runs (e.g. after the
 * ready event). On OK, *out_window is a window handle; release with
 * tauri_handle_close. Blocks the calling thread.
 */
int32_t tauri_window_create(uint64_t app, const char *config_json, uint64_t *out_window);

/*
 * Looks up the webview window with the given label. Returns ERR_NOT_FOUND if
 * no such window exists. On OK, *out_window is a window handle; release with
 * tauri_handle_close.
 */
int32_t tauri_app_get_window(uint64_t app, const char *label, uint64_t *out_window);

/*
 * Labels of all webview windows, as an owned JSON string array.
 */
int32_t tauri_app_window_labels(uint64_t app, char **out_labels_json);

/*
 * The window's label, as an owned string.
 */
int32_t tauri_window_label(uint64_t window, char **out_label);

/*
 * The window's current title, as an owned string.
 */
int32_t tauri_window_title(uint64_t window, char **out_title);

/*
 * The webview's current URL, as an owned string.
 */
int32_t tauri_window_url(uint64_t window, char **out_url);

/*
 * The window's DPI scale factor.
 */
int32_t tauri_window_scale_factor(uint64_t window, double *out_scale);

/*
 * The window's client-area size, in physical pixels.
 */
int32_t tauri_window_inner_size(uint64_t window, uint32_t *out_width, uint32_t *out_height);

/*
 * The window's outer size (including decorations), in physical pixels.
 */
int32_t tauri_window_outer_size(uint64_t window, uint32_t *out_width, uint32_t *out_height);

/*
 * The position of the window's client area, in physical pixels.
 */
int32_t tauri_window_inner_position(uint64_t window, int32_t *out_x, int32_t *out_y);

/*
 * The position of the window's top-left corner, in physical pixels.
 */
int32_t tauri_window_outer_position(uint64_t window, int32_t *out_x, int32_t *out_y);

/*
 * Whether the window is currently visible.
 */
int32_t tauri_window_is_visible(uint64_t window, bool *out_visible);

/*
 * Whether the window currently has focus.
 */
int32_t tauri_window_is_focused(uint64_t window, bool *out_focused);

/*
 * Whether the window is in fullscreen mode.
 */
int32_t tauri_window_is_fullscreen(uint64_t window, bool *out_fullscreen);

/*
 * Whether the window is maximized.
 */
int32_t tauri_window_is_maximized(uint64_t window, bool *out_maximized);

/*
 * Whether the window is minimized.
 */
int32_t tauri_window_is_minimized(uint64_t window, bool *out_minimized);

/*
 * Whether the window is resizable.
 */
int32_t tauri_window_is_resizable(uint64_t window, bool *out_resizable);

/*
 * Sets the window title.
 */
int32_t tauri_window_set_title(uint64_t window, const char *title);

/*
 * Resizes the window. physical=true interprets width/height as physical
 * pixels, otherwise as logical (DPI-scaled) pixels.
 */
int32_t tauri_window_set_size(uint64_t window, double width, double height, bool physical);

/*
 * Moves the window. physical=true interprets x/y as physical pixels, otherwise
 * as logical (DPI-scaled) pixels.
 */
int32_t tauri_window_set_position(uint64_t window, double x, double y, bool physical);

/*
 * Enters or leaves fullscreen mode.
 */
int32_t tauri_window_set_fullscreen(uint64_t window, bool fullscreen);

/*
 * Enables or disables window resizing.
 */
int32_t tauri_window_set_resizable(uint64_t window, bool resizable);

/*
 * Keeps the window above all other windows, or stops doing so.
 */
int32_t tauri_window_set_always_on_top(uint64_t window, bool always_on_top);

/*
 * Shows or hides the window decorations (title bar, borders).
 */
int32_t tauri_window_set_decorations(uint64_t window, bool decorations);

/*
 * Brings the window to front and focuses it.
 */
int32_t tauri_window_set_focus(uint64_t window);

/*
 * Sets the webview zoom level (1.0 = 100%).
 */
int32_t tauri_window_set_zoom(uint64_t window, double scale);

/*
 * Makes the window visible.
 */
int32_t tauri_window_show(uint64_t window);

/*
 * Hides the window.
 */
int32_t tauri_window_hide(uint64_t window);

/*
 * Centers the window on its current monitor.
 */
int32_t tauri_window_center(uint64_t window);

/*
 * Maximizes the window.
 */
int32_t tauri_window_maximize(uint64_t window);

/*
 * Restores the window from the maximized state.
 */
int32_t tauri_window_unmaximize(uint64_t window);

/*
 * Minimizes the window.
 */
int32_t tauri_window_minimize(uint64_t window);

/*
 * Restores the window from the minimized state.
 */
int32_t tauri_window_unminimize(uint64_t window);

/*
 * Requests the window to close (triggers close-requested handling). The window
 * handle stays valid until released with tauri_handle_close.
 */
int32_t tauri_window_close(uint64_t window);

/*
 * Destroys the window unconditionally (no close-requested event). The window
 * handle stays valid until released with tauri_handle_close.
 */
int32_t tauri_window_destroy(uint64_t window);

/*
 * Evaluates JavaScript in the window's webview.
 */
int32_t tauri_window_eval(uint64_t window, const char *js);

/*
 * Navigates the webview to the given URL.
 */
int32_t tauri_window_navigate(uint64_t window, const char *url);

/*
 * Reloads the webview's current page.
 */
int32_t tauri_window_reload(uint64_t window);

#ifdef __cplusplus
}
#endif

#endif /* TAURI_FFI_H */
