[package]
name = "tauri-schema-worker"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { workspace = true, features = ["http", "axum"] }
worker-macros = { workspace = true, features = ["http"] }
console_error_panic_hook = { workspace = true }
axum = { workspace = true }
tower-service = { workspace = true }
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(wasm_bindgen_unstable_test_coverage)',
] }
