// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

//! Experimental C ABI for embedding Tauri from non-Rust hosts (C, Node.js,
//! Python, Deno, …). M0 spike of `/ffi-bindings-plan.md`.
//!
//! # Conventions
//! - Every fallible function returns `i32` (`0` = ok, negative = error class)
//!   with out-values through pointer params. Details via
//!   [`tauri_last_error_message`].
//! - Objects are opaque `u64` handles (0 is never valid).
//! - Structured data crosses the boundary as UTF-8 JSON strings.
//! - Strings returned through `char**` out params are owned by the caller and
//!   must be released with [`tauri_string_free`].
//!
//! # Threading
//! - [`tauri_app_build`] and [`tauri_app_run`] must be called on the same
//!   thread — the process main thread on macOS. `tauri_app_run` blocks until
//!   the app exits (it wraps `App::run_return`).
//! - Everything else may be called from any thread; events are consumed by
//!   polling [`tauri_events_next`] from any thread (typically not the one
//!   blocked in `run`).
#![allow(clippy::missing_safety_doc)] // TODO(M1): per-fn safety docs, generated into the header

use std::collections::BTreeMap;
use std::ffi::{CStr, CString};
use std::os::raw::c_char;
use std::sync::{mpsc, Arc, Mutex};
use std::time::Duration;

use tauri::ipc::{InvokeBody, InvokeError, InvokeResponseBody};
use tauri::utils::acl::manifest::Manifest;
use tauri::utils::acl::resolved::Resolved;
use tauri::utils::config::Config;
use tauri::utils::PackageInfo;
use tauri::{Emitter, EventTarget, Listener, Manager, Pattern, RunEvent, WindowEvent};

// The runtime the cdylib is monomorphized to, selected by the `runtime-*` feature.
// The exported tauri_ffi C ABI is identical across runtimes; only the linked
// runtime (and thus the distributed library) differs.
#[cfg(feature = "runtime-cef")]
pub(crate) type Rt = tauri::Cef;
#[cfg(not(feature = "runtime-cef"))]
pub(crate) type Rt = tauri::Wry;
use crate::Rt as TauriRuntime;

// The CEF distribution version this library links against (e.g. `150.0.10`),
// embedded in a dedicated ELF section so the bindings CLI can read it *from the
// library file* — it can't `dlopen` a cef library to call an ABI function before
// the matching libcef is present, which is the chicken-and-egg the CLI resolves
// by downloading that CEF version. Only a linux cef build carries it: a PE image
// drops section names longer than 8 bytes and Mach-O caps them at 16, so macOS
// and Windows would each need their own encoding — and neither needs one yet,
// their cef support being `tauri dev` from a repo checkout, where the CEF
// distribution is staged next to the library and no download is required (see
// the CLI's `resolve_cef_distribution`).
#[cfg(all(feature = "runtime-cef", target_os = "linux"))]
#[used]
#[link_section = ".tauri_cef_version"]
static TAURI_FFI_CEF_VERSION: [u8; 32] = {
  const fn pad(s: &str) -> [u8; 32] {
    let bytes = s.as_bytes();
    assert!(bytes.len() < 32, "CEF version string does not fit in the section");
    let mut out = [0u8; 32];
    let mut i = 0;
    while i < bytes.len() {
      out[i] = bytes[i];
      i += 1;
    }
    out
  }
  pad(tauri::CEF_VERSION)
};

mod app;
mod assets;
mod error;
mod menu;
mod plugins;
mod state;
mod tray;
mod webview;
mod webview_window;
mod window;
mod winsupport;

use error::{
  catch, fail, ERR_CLOSED, ERR_GENERIC, ERR_INVALID_ARG, ERR_INVALID_HANDLE, ERR_TIMEOUT, OK,
};
use state::{AppState, BuilderState, Entry};

// Generated by build.rs: `static GLOBAL_API_SCRIPTS: &[&str]` — the
// window.__TAURI__ bundle advertised by the tauri crate's build script.
include!(concat!(env!("OUT_DIR"), "/global_api_scripts.rs"));

/// Core (and compiled-in plugin) permission manifests, collected by build.rs.
static ACL_MANIFESTS_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/acl-manifests.json"));

/// Applied when the host registers no capability of its own.
static DEFAULT_CAPABILITY: &str = r#"{
  "identifier": "tauri-ffi-default",
  "description": "Default capability granted by tauri-ffi when the host does not provide any.",
  "windows": ["*"],
  "permissions": ["core:default"]
}"#;

// Generated by build.rs from api-manifest.json: `const ABI_VERSION: u32`.
include!(concat!(env!("OUT_DIR"), "/abi_version.rs"));

// ---------------------------------------------------------------------------
// helpers

pub(crate) unsafe fn cstr<'a>(ptr: *const c_char) -> Result<&'a str, i32> {
  if ptr.is_null() {
    return Err(fail(ERR_INVALID_ARG, "unexpected null string argument"));
  }
  CStr::from_ptr(ptr)
    .to_str()
    .map_err(|_| fail(ERR_INVALID_ARG, "string argument is not valid UTF-8"))
}

macro_rules! try_cstr {
  ($ptr:expr) => {
    match unsafe { $crate::cstr($ptr) } {
      Ok(s) => s,
      Err(code) => return code,
    }
  };
}
pub(crate) use try_cstr;

/// Writes an owned, NUL-terminated copy of `value` to `out`; the caller
/// releases it with `tauri_string_free`.
pub(crate) fn write_owned_str(out: *mut *mut c_char, value: String) {
  let value = CString::new(value).unwrap_or_default();
  unsafe { *out = value.into_raw() };
}

// ---------------------------------------------------------------------------
// meta

#[no_mangle]
pub extern "C" fn tauri_ffi_version() -> *const c_char {
  static VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), "\0");
  VERSION.as_ptr().cast()
}

#[no_mangle]
pub extern "C" fn tauri_ffi_abi_version() -> u32 {
  ABI_VERSION
}

/// Borrowed pointer, valid until the next failing FFI call on this thread.
/// Returns null if no error has been recorded.
#[no_mangle]
pub extern "C" fn tauri_last_error_message() -> *const c_char {
  error::last_error_ptr()
}

/// Releases a string previously returned through a `char**` out param.
#[no_mangle]
pub unsafe extern "C" fn tauri_string_free(ptr: *mut c_char) {
  if !ptr.is_null() {
    drop(CString::from_raw(ptr));
  }
}

/// Drops a handle from the registry (builder, app or resolver).
#[no_mangle]
pub extern "C" fn tauri_handle_close(handle: u64) -> i32 {
  catch(|| {
    state::remove(handle);
    OK
  })
}

// ---------------------------------------------------------------------------
// app builder

/// Creates an app builder from a `tauri.conf.json`-shaped JSON string.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_builder_new(
  config_json: *const c_char,
  out_builder: *mut u64,
) -> i32 {
  catch(|| {
    let json = try_cstr!(config_json);
    if out_builder.is_null() {
      return fail(ERR_INVALID_ARG, "out_builder is null");
    }
    let config: Config = match serde_json::from_str(json) {
      Ok(config) => config,
      Err(e) => return fail(ERR_INVALID_ARG, format!("invalid config: {e}")),
    };
    let id = state::insert(Entry::Builder(BuilderState {
      config,
      assets_dir: None,
      assets_archive: None,
      assets_archive_bytes: None,
      dev: false,
      commands: Default::default(),
      capabilities: Vec::new(),
      plugins: Vec::new(),
    }));
    unsafe { *out_builder = id };
    OK
  })
}

/// Serves the app frontend (`WebviewUrl::App` paths) from a directory.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_builder_set_assets_dir(
  builder: u64,
  path: *const c_char,
) -> i32 {
  catch(|| {
    let path = try_cstr!(path);
    state::with_builder(builder, |b| {
      b.assets_dir = Some(path.into());
      OK
    })
  })
}

/// Serves the app frontend from a tauri-ffi assets archive (packed by
/// `tauri build`). Takes precedence over `tauri_app_builder_set_assets_dir`.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_builder_set_assets_archive(
  builder: u64,
  path: *const c_char,
) -> i32 {
  catch(|| {
    let path = try_cstr!(path);
    state::with_builder(builder, |b| {
      b.assets_archive = Some(path.into());
      OK
    })
  })
}

/// Serves the app frontend from an in-memory assets archive (same format as
/// `tauri_app_builder_set_assets_archive`, but the bytes are passed directly).
/// For hosts that embed the archive in their own binary (Deno `--include`,
/// Node SEA asset, PyInstaller data) rather than shipping it as a sibling file.
/// The bytes are copied; the caller may free them after the call returns. Takes
/// precedence over the dir/path asset variants.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_builder_set_assets_archive_bytes(
  builder: u64,
  bytes: *const u8,
  len: u32,
) -> i32 {
  catch(|| {
    if bytes.is_null() {
      return fail(ERR_INVALID_ARG, "bytes is null");
    }
    let data = unsafe { std::slice::from_raw_parts(bytes, len as usize) }.to_vec();
    let mut data = Some(data);
    state::with_builder(builder, |b| {
      b.assets_archive_bytes = data.take();
      OK
    })
  })
}

/// Enables dev mode: `WebviewUrl::App` windows load from `build.devUrl`
/// (when set), mirroring a Rust dev build.
#[no_mangle]
pub extern "C" fn tauri_app_builder_set_dev(builder: u64, dev: bool) -> i32 {
  catch(|| {
    state::with_builder(builder, |b| {
      b.dev = dev;
      OK
    })
  })
}

/// Registers a command name; invokes for it are delivered through
/// `tauri_events_next` as `{"type":"invoke",...}` messages.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_builder_register_command(
  builder: u64,
  name: *const c_char,
) -> i32 {
  catch(|| {
    let name = try_cstr!(name);
    state::with_builder(builder, |b| {
      b.commands.insert(name.to_string());
      OK
    })
  })
}

/// Adds a capability (JSON or TOML string, same format as capability files).
/// If none is added, a default granting `core:default` to all windows is used.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_builder_add_capability(
  builder: u64,
  capability: *const c_char,
) -> i32 {
  catch(|| {
    let capability = try_cstr!(capability);
    state::with_builder(builder, |b| {
      b.capabilities.push(capability.to_string());
      OK
    })
  })
}

/// Consumes the builder and builds the app. Must be called on the thread that
/// will run the event loop (the process main thread on macOS). Windows
/// declared in the config are created when the app runs.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_build(builder: u64, out_app: *mut u64) -> i32 {
  catch(|| {
    if out_app.is_null() {
      return fail(ERR_INVALID_ARG, "out_app is null");
    }
    let Some(Entry::Builder(builder_state)) = state::remove(builder) else {
      return fail(ERR_INVALID_HANDLE, "invalid builder handle");
    };
    match build_app(builder_state) {
      Ok(id) => {
        unsafe { *out_app = id };
        OK
      }
      Err(message) => fail(ERR_GENERIC, message),
    }
  })
}

fn build_app(builder_state: BuilderState) -> Result<u64, String> {
  let BuilderState {
    mut config,
    assets_dir,
    assets_archive,
    assets_archive_bytes,
    dev,
    commands,
    capabilities,
    plugins,
  } = builder_state;

  // Dev-mode emulation: the prebuilt cdylib is not compiled with the `dev`
  // cfg, but the runtime resolves `WebviewUrl::App` (and the Local origin for
  // ACL checks) against `frontend_dist` when it is a URL — so pointing it at
  // `devUrl` reproduces exactly what a Rust dev build does.
  if dev {
    if let Some(dev_url) = config.build.dev_url.clone() {
      config.build.frontend_dist = Some(tauri::utils::config::FrontendDist::Url(dev_url));
    }
  }

  // `cli` and `updater` read a required `plugins.<name>` config section and
  // fail app startup if it is absent (their config deserializes from `null`
  // and errors), so they are only registered when the host configured them.
  // Captured here because `config` is moved into the `Context` below.
  let cli_configured = config.plugins.0.contains_key("cli");
  let updater_configured = config.plugins.0.contains_key("updater");

  // ACL: embedded core manifests + a synthesized manifest per host plugin so
  // its `plugin:<name>|<command>` invokes resolve at runtime (`dynamic-acl`).
  let mut acl: BTreeMap<String, Manifest> = serde_json::from_str(ACL_MANIFESTS_JSON)
    .map_err(|e| format!("corrupt embedded ACL manifests: {e}"))?;
  for plugin in &plugins {
    acl.insert(plugin.name.clone(), plugin_manifest(plugin));
  }
  let plugin_names: Vec<String> = plugins.iter().map(|p| p.name.clone()).collect();
  let authority = tauri::runtime_authority!(acl, Resolved::default());

  let assets: Box<dyn tauri::Assets<TauriRuntime>> = if let Some(bytes) = assets_archive_bytes {
    Box::new(assets::ArchiveAssets::from_bytes(bytes)?)
  } else if let Some(archive) = assets_archive {
    Box::new(assets::ArchiveAssets::load(&archive)?)
  } else if let Some(dir) = assets_dir {
    Box::new(assets::DirAssets::new(dir))
  } else {
    Box::new(assets::EmptyAssets)
  };

  let package_info = PackageInfo {
    name: config
      .product_name
      .clone()
      .unwrap_or_else(|| "Tauri App".into()),
    version: config
      .version
      .as_deref()
      .unwrap_or("0.1.0")
      .parse()
      .map_err(|e| format!("invalid config version: {e}"))?,
    authors: "",
    description: "",
    crate_name: "tauri-ffi",
  };

  let global_api_scripts =
    (config.app.with_global_tauri && !GLOBAL_API_SCRIPTS.is_empty()).then_some(GLOBAL_API_SCRIPTS);

  let context = tauri::Context::<TauriRuntime>::new(
    config,
    assets,
    None, // default window icon — TODO(M1): tauri_app_builder_set_icon_rgba
    None, // app icon
    package_info,
    Pattern::Brownfield,
    authority,
    global_api_scripts,
  );

  // Serialized event stream: run events, subscribed events and invokes all
  // flow through one queue consumed by `tauri_events_next`.
  let (tx, rx) = mpsc::channel::<String>();

  let invoke_tx = tx.clone();
  let menu_tx = tx.clone();
  let mut builder = tauri::Builder::default()
    .invoke_handler(move |invoke: tauri::ipc::Invoke<TauriRuntime>| {
      let command = invoke.message.command();
      if !commands.contains(command) {
        return false; // tauri reports "command not found" to the frontend
      }
      let _ = invoke_tx.send(invoke_message_json(&invoke, command, None));
      true
    })
    // All menu clicks (app, window and tray menus) funnel into the event queue.
    .on_menu_event(move |_app, event| {
      let message = serde_json::json!({ "type": "menu-event", "id": event.id().0.clone() });
      let _ = menu_tx.send(message.to_string());
    });

  // Compiled-in first-party plugins (declared in Cargo.toml). Registering them
  // wires `plugin:<name>|<command>` invokes to the real Rust handlers and injects
  // each plugin's `window.__TAURI__.<name>` API script. Permissions are NOT granted
  // here: the host opts in per plugin via capabilities, and the manifests embedded by
  // build.rs make identifiers like `fs:default` resolvable at runtime (`dynamic-acl`).
  //
  // Two plugins are compiled in but intentionally not auto-activated because they need
  // host-supplied arguments and change process-wide behavior, so they belong behind a
  // dedicated FFI entry point rather than being forced on every app:
  //   * localhost       — `Builder::new(port)` requires a port to serve the frontend on.
  //   * single-instance — `init(callback)` requires a new-instance callback and makes the
  //                        process refuse to launch a second instance.
  builder = builder
    .plugin(tauri_plugin_fs::init())
    .plugin(tauri_plugin_clipboard_manager::init())
    .plugin(tauri_plugin_dialog::init())
    .plugin(tauri_plugin_http::init())
    .plugin(tauri_plugin_notification::init())
    .plugin(tauri_plugin_os::init())
    .plugin(tauri_plugin_process::init())
    .plugin(tauri_plugin_opener::init())
    .plugin(tauri_plugin_shell::init())
    .plugin(tauri_plugin_upload::init())
    .plugin(tauri_plugin_websocket::init())
    .plugin(tauri_plugin_positioner::init())
    .plugin(tauri_plugin_persisted_scope::init())
    .plugin(tauri_plugin_deep_link::init())
    .plugin(tauri_plugin_sql::Builder::new().build())
    .plugin(tauri_plugin_store::Builder::new().build())
    .plugin(tauri_plugin_log::Builder::new().build())
    .plugin(tauri_plugin_global_shortcut::Builder::new().build())
    .plugin(tauri_plugin_window_state::Builder::new().build())
    .plugin(tauri_plugin_autostart::Builder::new().build())
    // stronghold's password KDF needs a salt path, only known once the app has
    // resolved its data directory — register it from the setup hook like a normal app.
    // Best-effort: stronghold is opt-in (via capability), so a failure to resolve the
    // data dir or attach the plugin must not prevent the app from starting.
    .setup(|app| {
      use tauri::Manager;
      match app.path().app_local_data_dir() {
        Ok(dir) => {
          let salt_path = dir.join("stronghold-salt.txt");
          if let Err(e) = app
            .handle()
            .plugin(tauri_plugin_stronghold::Builder::with_argon2(&salt_path).build())
          {
            eprintln!("tauri-ffi: stronghold plugin unavailable: {e}");
          }
        }
        Err(e) => eprintln!("tauri-ffi: stronghold disabled, no app data dir: {e}"),
      }
      Ok(())
    });

  // Config-gated (see `cli_configured` / `updater_configured` above).
  if updater_configured {
    builder = builder.plugin(tauri_plugin_updater::Builder::new().build());
  }
  if cli_configured {
    builder = builder.plugin(tauri_plugin_cli::init());
  }

  // Each plugin gets a `tauri::plugin::Builder` whose invoke handler funnels
  // into the same event queue, tagged with the plugin name.
  for plugin in plugins {
    let state::PluginState {
      name,
      init_script,
      commands: plugin_commands,
    } = plugin;
    let plugin_tx = tx.clone();
    let plugin_name = name.clone();
    // `plugin::Builder::new` wants a `&'static str`; a plugin is created once
    // for the life of the app, so a one-time leak is acceptable.
    let leaked_name: &'static str = Box::leak(name.into_boxed_str());
    let mut plugin_builder = tauri::plugin::Builder::<TauriRuntime>::new(leaked_name)
      .invoke_handler(move |invoke: tauri::ipc::Invoke<TauriRuntime>| {
        // tauri strips the `plugin:<name>|` prefix before dispatch, so
        // `command()` is the bare command name here.
        let command = invoke.message.command();
        if !plugin_commands.contains(command) {
          return false;
        }
        let _ = plugin_tx.send(invoke_message_json(&invoke, command, Some(&plugin_name)));
        true
      });
    if let Some(js) = init_script {
      plugin_builder = plugin_builder.js_init_script(js);
    }
    let plugin = plugin_builder
      .try_build()
      .map_err(|e| format!("invalid plugin `{leaked_name}`: {e}"))?;
    builder = builder.plugin(plugin);
  }

  let app = builder
    .build(context)
    .map_err(|e| format!("failed to build app: {e}"))?;

  let handle = app.handle().clone();

  let mut capabilities = if capabilities.is_empty() {
    vec![DEFAULT_CAPABILITY.to_string()]
  } else {
    capabilities
  };
  // Grant every registered plugin's default permission to all windows — the
  // host opted in by registering the plugin's commands.
  if !plugin_names.is_empty() {
    let permissions: Vec<String> = plugin_names
      .iter()
      .map(|n| format!("{n}:default"))
      .collect();
    capabilities.push(
      serde_json::json!({
        "identifier": "tauri-ffi-plugins-default",
        "description": "Grants FFI-registered plugin default permissions to all windows.",
        "windows": ["*"],
        "permissions": permissions,
      })
      .to_string(),
    );
  }
  for capability in capabilities {
    handle
      .add_capability(capability)
      .map_err(|e| format!("invalid capability: {e}"))?;
  }

  let id = state::insert(Entry::App(Arc::new(AppState {
    handle,
    rx: Mutex::new(rx),
    tx,
  })));
  state::LOCAL_APPS.with(|apps| apps.borrow_mut().insert(id, app));
  Ok(id)
}

/// Registers the invoke's resolver and serializes it into a queue message.
/// `plugin` is `Some` for plugin commands (adds a `"plugin"` field).
fn invoke_message_json(
  invoke: &tauri::ipc::Invoke<TauriRuntime>,
  command: &str,
  plugin: Option<&str>,
) -> String {
  let payload = match invoke.message.payload() {
    InvokeBody::Json(value) => value.clone(),
    // TODO(M1): raw (binary) payloads
    InvokeBody::Raw(_) => serde_json::Value::Null,
  };
  let resolver_id = state::insert(Entry::Resolver(invoke.resolver.clone()));
  let mut message = serde_json::json!({
    "type": "invoke",
    "id": resolver_id,
    "command": command,
    "payload": payload,
    "webview": invoke.message.webview_ref().label(),
  });
  if let Some(plugin) = plugin {
    message["plugin"] = serde_json::Value::String(plugin.to_string());
  }
  message.to_string()
}

/// Synthesizes an ACL manifest granting a host plugin's commands. The default
/// permission `<name>:default` (referenced by the default capability) allows
/// every registered command, so `plugin:<name>|<command>` resolves at runtime.
fn plugin_manifest(plugin: &state::PluginState) -> Manifest {
  use tauri::utils::acl::manifest::{DefaultPermission, PermissionFile};
  use tauri::utils::acl::{Commands, Permission};

  let commands = plugin.commands.iter().cloned().collect();
  let permission = Permission {
    version: None,
    identifier: "allow-all".to_string(),
    description: None,
    commands: Commands {
      allow: commands,
      deny: Vec::new(),
    },
    scope: Default::default(),
    platforms: None,
  };
  let file = PermissionFile {
    default: Some(DefaultPermission {
      version: None,
      description: None,
      permissions: vec!["allow-all".to_string()],
    }),
    set: Vec::new(),
    permission: vec![permission],
    commands: Vec::new(),
  };
  Manifest::new(vec![file], None)
}

// ---------------------------------------------------------------------------
// run loop

/// Runs the event loop, blocking the calling thread until the app exits.
/// Must be called on the thread that called `tauri_app_build`. Run events are
/// also delivered through the event queue (`{"type":"ready"}`, `"exit"`, …).
#[no_mangle]
pub unsafe extern "C" fn tauri_app_run(app: u64, out_exit_code: *mut i32) -> i32 {
  catch(|| {
    let Some(local_app) = state::LOCAL_APPS.with(|apps| apps.borrow_mut().remove(&app)) else {
      return fail(
        ERR_INVALID_HANDLE,
        "unknown app handle — tauri_app_run must be called on the thread that called tauri_app_build",
      );
    };
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    let tx = app_state.tx.clone();
    drop(app_state);

    let exit_code = local_app.run_return(move |_handle, event| {
      if let Some(message) = run_event_json(&event) {
        let _ = tx.send(message);
      }
    });

    if !out_exit_code.is_null() {
      unsafe { *out_exit_code = exit_code };
    }
    OK
  })
}

/// Requests app exit from any thread.
#[no_mangle]
pub extern "C" fn tauri_app_exit(app: u64, code: i32) -> i32 {
  catch(|| {
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    app_state.handle.exit(code);
    OK
  })
}

/// The app's resolved configuration, as an owned JSON string.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_config(app: u64, out_config_json: *mut *mut c_char) -> i32 {
  catch(|| {
    if out_config_json.is_null() {
      return fail(ERR_INVALID_ARG, "out_config_json is null");
    }
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    let json = serde_json::to_string(app_state.handle.config()).unwrap_or_else(|_| "null".into());
    write_owned_str(out_config_json, json);
    OK
  })
}

/// The app package info, as an owned JSON object.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_package_info(app: u64, out_info_json: *mut *mut c_char) -> i32 {
  catch(|| {
    if out_info_json.is_null() {
      return fail(ERR_INVALID_ARG, "out_info_json is null");
    }
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    let info = app_state.handle.package_info();
    let json = serde_json::json!({
      "name": info.name,
      "version": info.version.to_string(),
      "authors": info.authors,
      "description": info.description,
      "crateName": info.crate_name,
    })
    .to_string();
    write_owned_str(out_info_json, json);
    OK
  })
}

fn run_event_json(event: &RunEvent) -> Option<String> {
  let value = match event {
    RunEvent::Ready => serde_json::json!({ "type": "ready" }),
    RunEvent::Exit => serde_json::json!({ "type": "exit" }),
    RunEvent::ExitRequested { code, .. } => {
      // Queue consumers cannot veto synchronously; exit policies are the
      // M1 answer (see plan §4.4).
      serde_json::json!({ "type": "exit-requested", "code": code })
    }
    RunEvent::WindowEvent { label, event, .. } => {
      let window_event = match event {
        WindowEvent::CloseRequested { .. } => serde_json::json!({ "kind": "close-requested" }),
        WindowEvent::Destroyed => serde_json::json!({ "kind": "destroyed" }),
        WindowEvent::Focused(focused) => {
          serde_json::json!({ "kind": "focused", "focused": focused })
        }
        WindowEvent::Moved(position) => {
          serde_json::json!({ "kind": "moved", "x": position.x, "y": position.y })
        }
        WindowEvent::Resized(size) => {
          serde_json::json!({ "kind": "resized", "width": size.width, "height": size.height })
        }
        _ => return None,
      };
      serde_json::json!({ "type": "window-event", "label": label, "event": window_event })
    }
    _ => return None,
  };
  Some(value.to_string())
}

// ---------------------------------------------------------------------------
// event queue

/// Blocks up to `timeout_ms` for the next queued message (run events,
/// subscribed events, invokes). On `TAURI_OK`, `*out_json` is an owned string
/// — free it with `tauri_string_free`. Returns `ERR_TIMEOUT` (-3) on timeout
/// and `ERR_CLOSED` (-4) once the app has shut down.
#[no_mangle]
pub unsafe extern "C" fn tauri_events_next(
  app: u64,
  timeout_ms: u32,
  out_json: *mut *mut c_char,
) -> i32 {
  catch(|| {
    if out_json.is_null() {
      return fail(ERR_INVALID_ARG, "out_json is null");
    }
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    let rx = app_state.rx.lock().unwrap();
    match rx.recv_timeout(Duration::from_millis(timeout_ms.into())) {
      Ok(message) => {
        write_owned_str(out_json, message);
        OK
      }
      Err(mpsc::RecvTimeoutError::Timeout) => ERR_TIMEOUT,
      Err(mpsc::RecvTimeoutError::Disconnected) => ERR_CLOSED,
    }
  })
}

// ---------------------------------------------------------------------------
// events

/// Emits an event to all listeners (Rust, frontend and FFI subscribers).
/// `payload_json` must be valid JSON.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_emit(
  app: u64,
  event: *const c_char,
  payload_json: *const c_char,
) -> i32 {
  catch(|| {
    let event = try_cstr!(event);
    let payload = try_cstr!(payload_json);
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    match app_state.handle.emit_str(event, payload.to_string()) {
      Ok(()) => OK,
      Err(e) => fail(ERR_GENERIC, format!("emit failed: {e}")),
    }
  })
}

/// Emits an event to every target with the given label.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_emit_to(
  app: u64,
  label: *const c_char,
  event: *const c_char,
  payload_json: *const c_char,
) -> i32 {
  catch(|| {
    let label = try_cstr!(label);
    let event = try_cstr!(event);
    let payload = try_cstr!(payload_json);
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    match app_state
      .handle
      .emit_str_to(EventTarget::labeled(label), event, payload.to_string())
    {
      Ok(()) => OK,
      Err(e) => fail(ERR_GENERIC, format!("emit_to failed: {e}")),
    }
  })
}

/// Subscribes to an event (any target). Deliveries arrive on the event queue
/// as `{"type":"event","event":...,"id":...,"payload":...}`.
#[no_mangle]
pub unsafe extern "C" fn tauri_app_listen(
  app: u64,
  event: *const c_char,
  out_listener: *mut u32,
) -> i32 {
  catch(|| {
    let event = try_cstr!(event);
    if out_listener.is_null() {
      return fail(ERR_INVALID_ARG, "out_listener is null");
    }
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    let tx = app_state.tx.clone();
    let name = event.to_string();
    let listener_id = app_state.handle.listen_any(name.clone(), move |event| {
      let payload: serde_json::Value = serde_json::from_str(event.payload())
        .unwrap_or_else(|_| serde_json::Value::String(event.payload().to_string()));
      let message = serde_json::json!({
        "type": "event",
        "event": name,
        "id": event.id(),
        "payload": payload,
      });
      let _ = tx.send(message.to_string());
    });
    unsafe { *out_listener = listener_id };
    OK
  })
}

#[no_mangle]
pub extern "C" fn tauri_app_unlisten(app: u64, listener: u32) -> i32 {
  catch(|| {
    let Some(app_state) = state::app(app) else {
      return fail(ERR_INVALID_HANDLE, "invalid app handle");
    };
    app_state.handle.unlisten(listener);
    OK
  })
}

// ---------------------------------------------------------------------------
// invoke (commands)

/// Resolves a pending invoke with a JSON value. Consumes the resolver handle.
/// Callable from any thread, any time after the invoke was delivered.
#[no_mangle]
pub unsafe extern "C" fn tauri_invoke_resolve(resolver: u64, json: *const c_char) -> i32 {
  catch(|| {
    let json = try_cstr!(json);
    let Some(Entry::Resolver(resolver)) = state::remove(resolver) else {
      return fail(ERR_INVALID_HANDLE, "invalid resolver handle");
    };
    resolver.respond(Ok::<_, InvokeError>(InvokeResponseBody::Json(
      json.to_owned(),
    )));
    OK
  })
}

/// Rejects a pending invoke with a JSON value. Consumes the resolver handle.
#[no_mangle]
pub unsafe extern "C" fn tauri_invoke_reject(resolver: u64, json: *const c_char) -> i32 {
  catch(|| {
    let json = try_cstr!(json);
    let Some(Entry::Resolver(resolver)) = state::remove(resolver) else {
      return fail(ERR_INVALID_HANDLE, "invalid resolver handle");
    };
    let value: serde_json::Value =
      serde_json::from_str(json).unwrap_or_else(|_| serde_json::Value::String(json.to_owned()));
    resolver.respond(Err::<InvokeResponseBody, _>(InvokeError(value)));
    OK
  })
}
