use tauri_runtime::device_events::{Code, DeviceEvent, MouseScrollDelta};

pub fn map_device_event(event: tao::event::DeviceEvent) -> Option<DeviceEvent> {
  match event {
    tao::event::DeviceEvent::Added => Some(DeviceEvent::Added),
    tao::event::DeviceEvent::Removed => Some(DeviceEvent::Removed),
    tao::event::DeviceEvent::MouseMotion { delta, .. } => Some(DeviceEvent::MouseMotion { delta }),
    tao::event::DeviceEvent::MouseWheel { delta, .. } => match delta {
      tao::event::MouseScrollDelta::LineDelta(x, y) => Some(DeviceEvent::MouseWheel {
        delta: MouseScrollDelta::LineDelta(x, y),
      }),
      tao::event::MouseScrollDelta::PixelDelta(pos) => Some(DeviceEvent::MouseWheel {
        delta: MouseScrollDelta::PixelDelta(pos),
      }),
      _ => None,
    },
    tao::event::DeviceEvent::Motion { axis, value, .. } => {
      Some(DeviceEvent::Motion { axis, value })
    }
    tao::event::DeviceEvent::Button { button, state, .. } => Some(DeviceEvent::Button {
      button,
      state: map_element_state(state)?,
    }),
    tao::event::DeviceEvent::Key(raw_key_event) => {
      let physical_key = raw_key_event.physical_key;
      let state = map_element_state(raw_key_event.state)?;
      Some(DeviceEvent::Key {
        pysical_key: map_physical_key(physical_key)?,
        state,
      })
    }
    tao::event::DeviceEvent::Text { codepoint, .. } => Some(DeviceEvent::Text { codepoint }),
    _ => None,
  }
}

fn map_element_state(
  state: tao::event::ElementState,
) -> Option<tauri_runtime::device_events::KeyState> {
  match state {
    tao::event::ElementState::Pressed => Some(tauri_runtime::device_events::KeyState::Down),
    tao::event::ElementState::Released => Some(tauri_runtime::device_events::KeyState::Up),
    _ => None,
  }
}

fn map_physical_key(event: tao::keyboard::KeyCode) -> Option<Code> {
  match event {
    tao::keyboard::KeyCode::Unidentified(native_key_code) => todo!(),
    tao::keyboard::KeyCode::Backquote => Some(Code::Backquote),
    tao::keyboard::KeyCode::Backslash => Some(Code::Backslash),
    tao::keyboard::KeyCode::BracketLeft => Some(Code::BracketLeft),
    tao::keyboard::KeyCode::BracketRight => Some(Code::BracketRight),
    tao::keyboard::KeyCode::Comma => Some(Code::Comma),
    tao::keyboard::KeyCode::Digit0 => Some(Code::Digit0),
    tao::keyboard::KeyCode::Digit1 => Some(Code::Digit1),
    tao::keyboard::KeyCode::Digit2 => Some(Code::Digit2),
    tao::keyboard::KeyCode::Digit3 => Some(Code::Digit3),
    tao::keyboard::KeyCode::Digit4 => Some(Code::Digit4),
    tao::keyboard::KeyCode::Digit5 => Some(Code::Digit5),
    tao::keyboard::KeyCode::Digit6 => Some(Code::Digit6),
    tao::keyboard::KeyCode::Digit7 => Some(Code::Digit7),
    tao::keyboard::KeyCode::Digit8 => Some(Code::Digit8),
    tao::keyboard::KeyCode::Digit9 => Some(Code::Digit9),
    tao::keyboard::KeyCode::Equal => Some(Code::Equal),
    tao::keyboard::KeyCode::IntlBackslash => Some(Code::IntlBackslash),
    tao::keyboard::KeyCode::IntlRo => Some(Code::IntlRo),
    tao::keyboard::KeyCode::IntlYen => Some(Code::IntlYen),
    tao::keyboard::KeyCode::KeyA => Some(Code::KeyA),
    tao::keyboard::KeyCode::KeyB => Some(Code::KeyB),
    tao::keyboard::KeyCode::KeyC => Some(Code::KeyC),
    tao::keyboard::KeyCode::KeyD => Some(Code::KeyD),
    tao::keyboard::KeyCode::KeyE => Some(Code::KeyE),
    tao::keyboard::KeyCode::KeyF => Some(Code::KeyF),
    tao::keyboard::KeyCode::KeyG => Some(Code::KeyG),
    tao::keyboard::KeyCode::KeyH => Some(Code::KeyH),
    tao::keyboard::KeyCode::KeyI => Some(Code::KeyI),
    tao::keyboard::KeyCode::KeyJ => Some(Code::KeyJ),
    tao::keyboard::KeyCode::KeyK => Some(Code::KeyK),
    tao::keyboard::KeyCode::KeyL => Some(Code::KeyL),
    tao::keyboard::KeyCode::KeyM => Some(Code::KeyM),
    tao::keyboard::KeyCode::KeyN => Some(Code::KeyN),
    tao::keyboard::KeyCode::KeyO => Some(Code::KeyO),
    tao::keyboard::KeyCode::KeyP => Some(Code::KeyP),
    tao::keyboard::KeyCode::KeyQ => Some(Code::KeyQ),
    tao::keyboard::KeyCode::KeyR => Some(Code::KeyR),
    tao::keyboard::KeyCode::KeyS => Some(Code::KeyS),
    tao::keyboard::KeyCode::KeyT => Some(Code::KeyT),
    tao::keyboard::KeyCode::KeyU => Some(Code::KeyU),
    tao::keyboard::KeyCode::KeyV => Some(Code::KeyV),
    tao::keyboard::KeyCode::KeyW => Some(Code::KeyW),
    tao::keyboard::KeyCode::KeyX => Some(Code::KeyX),
    tao::keyboard::KeyCode::KeyY => Some(Code::KeyY),
    tao::keyboard::KeyCode::KeyZ => Some(Code::KeyZ),
    tao::keyboard::KeyCode::Minus => Some(Code::Minus),
    // could be wrong convertion??
    tao::keyboard::KeyCode::Plus => Some(Code::Equal),
    tao::keyboard::KeyCode::Period => Some(Code::Period),
    tao::keyboard::KeyCode::Quote => Some(Code::Quote),
    tao::keyboard::KeyCode::Semicolon => Some(Code::Semicolon),
    tao::keyboard::KeyCode::Slash => Some(Code::Slash),
    tao::keyboard::KeyCode::AltLeft => Some(Code::AltLeft),
    tao::keyboard::KeyCode::AltRight => Some(Code::AltRight),
    tao::keyboard::KeyCode::Backspace => Some(Code::Backspace),
    tao::keyboard::KeyCode::CapsLock => Some(Code::CapsLock),
    tao::keyboard::KeyCode::ContextMenu => Some(Code::ContextMenu),
    tao::keyboard::KeyCode::ControlLeft => Some(Code::ControlLeft),
    tao::keyboard::KeyCode::ControlRight => Some(Code::ControlRight),
    tao::keyboard::KeyCode::Enter => Some(Code::Enter),
    tao::keyboard::KeyCode::SuperLeft => Some(Code::MetaLeft),
    tao::keyboard::KeyCode::SuperRight => Some(Code::MetaRight),
    tao::keyboard::KeyCode::ShiftLeft => Some(Code::ShiftLeft),
    tao::keyboard::KeyCode::ShiftRight => Some(Code::ShiftRight),
    tao::keyboard::KeyCode::Space => Some(Code::Space),
    tao::keyboard::KeyCode::Tab => Some(Code::Tab),
    tao::keyboard::KeyCode::Convert => Some(Code::Convert),
    tao::keyboard::KeyCode::KanaMode => Some(Code::KanaMode),
    tao::keyboard::KeyCode::Lang1 => Some(Code::Lang1),
    tao::keyboard::KeyCode::Lang2 => Some(Code::Lang2),
    tao::keyboard::KeyCode::Lang3 => Some(Code::Lang3),
    tao::keyboard::KeyCode::Lang4 => Some(Code::Lang4),
    tao::keyboard::KeyCode::Lang5 => Some(Code::Lang5),
    tao::keyboard::KeyCode::NonConvert => Some(Code::NonConvert),
    tao::keyboard::KeyCode::Delete => Some(Code::Delete),
    tao::keyboard::KeyCode::End => Some(Code::End),
    tao::keyboard::KeyCode::Help => Some(Code::Help),
    tao::keyboard::KeyCode::Home => Some(Code::Home),
    tao::keyboard::KeyCode::Insert => Some(Code::Insert),
    tao::keyboard::KeyCode::PageDown => Some(Code::PageDown),
    tao::keyboard::KeyCode::PageUp => Some(Code::PageUp),
    tao::keyboard::KeyCode::ArrowDown => Some(Code::ArrowDown),
    tao::keyboard::KeyCode::ArrowLeft => Some(Code::ArrowLeft),
    tao::keyboard::KeyCode::ArrowRight => Some(Code::ArrowRight),
    tao::keyboard::KeyCode::ArrowUp => Some(Code::ArrowUp),
    tao::keyboard::KeyCode::NumLock => Some(Code::NumLock),
    tao::keyboard::KeyCode::Numpad0 => Some(Code::Numpad0),
    tao::keyboard::KeyCode::Numpad1 => Some(Code::Numpad1),
    tao::keyboard::KeyCode::Numpad2 => Some(Code::Numpad2),
    tao::keyboard::KeyCode::Numpad3 => Some(Code::Numpad3),
    tao::keyboard::KeyCode::Numpad4 => Some(Code::Numpad4),
    tao::keyboard::KeyCode::Numpad5 => Some(Code::Numpad5),
    tao::keyboard::KeyCode::Numpad6 => Some(Code::Numpad6),
    tao::keyboard::KeyCode::Numpad7 => Some(Code::Numpad7),
    tao::keyboard::KeyCode::Numpad8 => Some(Code::Numpad8),
    tao::keyboard::KeyCode::Numpad9 => Some(Code::Numpad9),
    tao::keyboard::KeyCode::NumpadAdd => Some(Code::NumpadAdd),
    tao::keyboard::KeyCode::NumpadBackspace => Some(Code::NumpadBackspace),
    tao::keyboard::KeyCode::NumpadClear => Some(Code::NumpadClear),
    tao::keyboard::KeyCode::NumpadClearEntry => Some(Code::NumpadClearEntry),
    tao::keyboard::KeyCode::NumpadComma => Some(Code::NumpadComma),
    tao::keyboard::KeyCode::NumpadDecimal => Some(Code::NumpadDecimal),
    tao::keyboard::KeyCode::NumpadDivide => Some(Code::NumpadDivide),
    tao::keyboard::KeyCode::NumpadEnter => Some(Code::NumpadEnter),
    tao::keyboard::KeyCode::NumpadEqual => Some(Code::NumpadEqual),
    tao::keyboard::KeyCode::NumpadHash => Some(Code::NumpadHash),
    tao::keyboard::KeyCode::NumpadMemoryAdd => Some(Code::NumpadMemoryAdd),
    tao::keyboard::KeyCode::NumpadMemoryClear => Some(Code::NumpadMemoryClear),
    tao::keyboard::KeyCode::NumpadMemoryRecall => Some(Code::NumpadMemoryRecall),
    tao::keyboard::KeyCode::NumpadMemoryStore => Some(Code::NumpadMemoryStore),
    tao::keyboard::KeyCode::NumpadMemorySubtract => Some(Code::NumpadMemorySubtract),
    tao::keyboard::KeyCode::NumpadMultiply => Some(Code::NumpadMultiply),
    tao::keyboard::KeyCode::NumpadParenLeft => Some(Code::NumpadParenLeft),
    tao::keyboard::KeyCode::NumpadParenRight => Some(Code::NumpadParenRight),
    tao::keyboard::KeyCode::NumpadStar => Some(Code::NumpadStar),
    tao::keyboard::KeyCode::NumpadSubtract => Some(Code::NumpadSubtract),
    tao::keyboard::KeyCode::Escape => Some(Code::Escape),
    tao::keyboard::KeyCode::Fn => Some(Code::Fn),
    tao::keyboard::KeyCode::FnLock => Some(Code::FnLock),
    tao::keyboard::KeyCode::PrintScreen => Some(Code::PrintScreen),
    tao::keyboard::KeyCode::ScrollLock => Some(Code::ScrollLock),
    tao::keyboard::KeyCode::Pause => Some(Code::Pause),
    tao::keyboard::KeyCode::BrowserBack => Some(Code::BrowserBack),
    tao::keyboard::KeyCode::BrowserFavorites => Some(Code::BrowserFavorites),
    tao::keyboard::KeyCode::BrowserForward => Some(Code::BrowserForward),
    tao::keyboard::KeyCode::BrowserHome => Some(Code::BrowserHome),
    tao::keyboard::KeyCode::BrowserRefresh => Some(Code::BrowserRefresh),
    tao::keyboard::KeyCode::BrowserSearch => Some(Code::BrowserSearch),
    tao::keyboard::KeyCode::BrowserStop => Some(Code::BrowserStop),
    tao::keyboard::KeyCode::Eject => Some(Code::Eject),
    tao::keyboard::KeyCode::LaunchApp1 => Some(Code::LaunchApp1),
    tao::keyboard::KeyCode::LaunchApp2 => Some(Code::LaunchApp2),
    tao::keyboard::KeyCode::LaunchMail => Some(Code::LaunchMail),
    tao::keyboard::KeyCode::MediaPlayPause => Some(Code::MediaPlayPause),
    tao::keyboard::KeyCode::MediaSelect => Some(Code::MediaSelect),
    tao::keyboard::KeyCode::MediaStop => Some(Code::MediaStop),
    tao::keyboard::KeyCode::MediaTrackNext => Some(Code::MediaTrackNext),
    tao::keyboard::KeyCode::MediaTrackPrevious => Some(Code::MediaTrackPrevious),
    tao::keyboard::KeyCode::Power => Some(Code::Power),
    tao::keyboard::KeyCode::Sleep => Some(Code::Sleep),
    tao::keyboard::KeyCode::AudioVolumeDown => Some(Code::AudioVolumeDown),
    tao::keyboard::KeyCode::AudioVolumeMute => Some(Code::AudioVolumeMute),
    tao::keyboard::KeyCode::AudioVolumeUp => Some(Code::AudioVolumeUp),
    tao::keyboard::KeyCode::WakeUp => Some(Code::WakeUp),
    tao::keyboard::KeyCode::Hyper => Some(Code::Hyper),
    tao::keyboard::KeyCode::Turbo => Some(Code::Turbo),
    tao::keyboard::KeyCode::Abort => Some(Code::Abort),
    tao::keyboard::KeyCode::Resume => Some(Code::Resume),
    tao::keyboard::KeyCode::Suspend => Some(Code::Suspend),
    tao::keyboard::KeyCode::Again => Some(Code::Again),
    tao::keyboard::KeyCode::Copy => Some(Code::Copy),
    tao::keyboard::KeyCode::Cut => Some(Code::Cut),
    tao::keyboard::KeyCode::Find => Some(Code::Find),
    tao::keyboard::KeyCode::Open => Some(Code::Open),
    tao::keyboard::KeyCode::Paste => Some(Code::Paste),
    tao::keyboard::KeyCode::Props => Some(Code::Props),
    tao::keyboard::KeyCode::Select => Some(Code::Select),
    tao::keyboard::KeyCode::Undo => Some(Code::Undo),
    tao::keyboard::KeyCode::Hiragana => Some(Code::Hiragana),
    tao::keyboard::KeyCode::Katakana => Some(Code::Katakana),
    tao::keyboard::KeyCode::F1 => Some(Code::F1),
    tao::keyboard::KeyCode::F2 => Some(Code::F2),
    tao::keyboard::KeyCode::F3 => Some(Code::F3),
    tao::keyboard::KeyCode::F4 => Some(Code::F4),
    tao::keyboard::KeyCode::F5 => Some(Code::F5),
    tao::keyboard::KeyCode::F6 => Some(Code::F6),
    tao::keyboard::KeyCode::F7 => Some(Code::F7),
    tao::keyboard::KeyCode::F8 => Some(Code::F8),
    tao::keyboard::KeyCode::F9 => Some(Code::F9),
    tao::keyboard::KeyCode::F10 => Some(Code::F10),
    tao::keyboard::KeyCode::F11 => Some(Code::F11),
    tao::keyboard::KeyCode::F12 => Some(Code::F12),
    tao::keyboard::KeyCode::F13 => Some(Code::F13),
    tao::keyboard::KeyCode::F14 => Some(Code::F14),
    tao::keyboard::KeyCode::F15 => Some(Code::F15),
    tao::keyboard::KeyCode::F16 => Some(Code::F16),
    tao::keyboard::KeyCode::F17 => Some(Code::F17),
    tao::keyboard::KeyCode::F18 => Some(Code::F18),
    tao::keyboard::KeyCode::F19 => Some(Code::F19),
    tao::keyboard::KeyCode::F20 => Some(Code::F20),
    tao::keyboard::KeyCode::F21 => Some(Code::F21),
    tao::keyboard::KeyCode::F22 => Some(Code::F22),
    tao::keyboard::KeyCode::F23 => Some(Code::F23),
    tao::keyboard::KeyCode::F24 => Some(Code::F24),
    tao::keyboard::KeyCode::F25 => Some(Code::F25),
    tao::keyboard::KeyCode::F26 => Some(Code::F26),
    tao::keyboard::KeyCode::F27 => Some(Code::F27),
    tao::keyboard::KeyCode::F28 => Some(Code::F28),
    tao::keyboard::KeyCode::F29 => Some(Code::F29),
    tao::keyboard::KeyCode::F30 => Some(Code::F30),
    tao::keyboard::KeyCode::F31 => Some(Code::F31),
    tao::keyboard::KeyCode::F32 => Some(Code::F32),
    tao::keyboard::KeyCode::F33 => Some(Code::F33),
    tao::keyboard::KeyCode::F34 => Some(Code::F34),
    tao::keyboard::KeyCode::F35 => Some(Code::F35),
    _ => None,
  }
}
