// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// Generated by bindings/bindgen/generate.mjs from crates/tauri-ffi/api-manifest.json — do not edit.

export const ABI_VERSION = 2

export const CODES = {
  OK: 0,
  GENERIC: -1,
  INVALID_HANDLE: -2,
  TIMEOUT: -3,
  CLOSED: -4,
  INVALID_ARG: -5,
  PANIC: -7,
  NOT_FOUND: -8
}

export const DECLS = {
  ffiVersion: 'const char * tauri_ffi_version()',
  ffiAbiVersion: 'uint32_t tauri_ffi_abi_version()',
  lastErrorMessage: 'const char * tauri_last_error_message()',
  stringFree: 'void tauri_string_free(void *str)',
  handleClose: 'int32_t tauri_handle_close(uint64_t handle)',
  appBuilderNew: 'int32_t tauri_app_builder_new(const char *config_json, _Out_ uint64_t *out_builder)',
  appBuilderSetAssetsDir: 'int32_t tauri_app_builder_set_assets_dir(uint64_t builder, const char *path)',
  appBuilderRegisterCommand: 'int32_t tauri_app_builder_register_command(uint64_t builder, const char *name)',
  appBuilderAddCapability: 'int32_t tauri_app_builder_add_capability(uint64_t builder, const char *capability)',
  appBuild: 'int32_t tauri_app_build(uint64_t builder, _Out_ uint64_t *out_app)',
  appRun: 'int32_t tauri_app_run(uint64_t app, _Out_ int32_t *out_exit_code)',
  appExit: 'int32_t tauri_app_exit(uint64_t app, int32_t code)',
  eventsNext: 'int32_t tauri_events_next(uint64_t app, uint32_t timeout_ms, _Out_ void **out_json)',
  appEmit: 'int32_t tauri_app_emit(uint64_t app, const char *event, const char *payload_json)',
  appEmitTo: 'int32_t tauri_app_emit_to(uint64_t app, const char *label, const char *event, const char *payload_json)',
  appListen: 'int32_t tauri_app_listen(uint64_t app, const char *event, _Out_ uint32_t *out_listener)',
  appUnlisten: 'int32_t tauri_app_unlisten(uint64_t app, uint32_t listener)',
  invokeResolve: 'int32_t tauri_invoke_resolve(uint64_t resolver, const char *json)',
  invokeReject: 'int32_t tauri_invoke_reject(uint64_t resolver, const char *json)',
  windowCreate: 'int32_t tauri_window_create(uint64_t app, const char *config_json, _Out_ uint64_t *out_window)',
  appGetWindow: 'int32_t tauri_app_get_window(uint64_t app, const char *label, _Out_ uint64_t *out_window)',
  appWindowLabels: 'int32_t tauri_app_window_labels(uint64_t app, _Out_ void **out_labels_json)',
  windowLabel: 'int32_t tauri_window_label(uint64_t window, _Out_ void **out_label)',
  windowTitle: 'int32_t tauri_window_title(uint64_t window, _Out_ void **out_title)',
  windowUrl: 'int32_t tauri_window_url(uint64_t window, _Out_ void **out_url)',
  windowScaleFactor: 'int32_t tauri_window_scale_factor(uint64_t window, _Out_ double *out_scale)',
  windowInnerSize: 'int32_t tauri_window_inner_size(uint64_t window, _Out_ uint32_t *out_width, _Out_ uint32_t *out_height)',
  windowOuterSize: 'int32_t tauri_window_outer_size(uint64_t window, _Out_ uint32_t *out_width, _Out_ uint32_t *out_height)',
  windowInnerPosition: 'int32_t tauri_window_inner_position(uint64_t window, _Out_ int32_t *out_x, _Out_ int32_t *out_y)',
  windowOuterPosition: 'int32_t tauri_window_outer_position(uint64_t window, _Out_ int32_t *out_x, _Out_ int32_t *out_y)',
  windowIsVisible: 'int32_t tauri_window_is_visible(uint64_t window, _Out_ bool *out_visible)',
  windowIsFocused: 'int32_t tauri_window_is_focused(uint64_t window, _Out_ bool *out_focused)',
  windowIsFullscreen: 'int32_t tauri_window_is_fullscreen(uint64_t window, _Out_ bool *out_fullscreen)',
  windowIsMaximized: 'int32_t tauri_window_is_maximized(uint64_t window, _Out_ bool *out_maximized)',
  windowIsMinimized: 'int32_t tauri_window_is_minimized(uint64_t window, _Out_ bool *out_minimized)',
  windowIsResizable: 'int32_t tauri_window_is_resizable(uint64_t window, _Out_ bool *out_resizable)',
  windowSetTitle: 'int32_t tauri_window_set_title(uint64_t window, const char *title)',
  windowSetSize: 'int32_t tauri_window_set_size(uint64_t window, double width, double height, bool physical)',
  windowSetPosition: 'int32_t tauri_window_set_position(uint64_t window, double x, double y, bool physical)',
  windowSetFullscreen: 'int32_t tauri_window_set_fullscreen(uint64_t window, bool fullscreen)',
  windowSetResizable: 'int32_t tauri_window_set_resizable(uint64_t window, bool resizable)',
  windowSetAlwaysOnTop: 'int32_t tauri_window_set_always_on_top(uint64_t window, bool always_on_top)',
  windowSetDecorations: 'int32_t tauri_window_set_decorations(uint64_t window, bool decorations)',
  windowSetFocus: 'int32_t tauri_window_set_focus(uint64_t window)',
  windowSetZoom: 'int32_t tauri_window_set_zoom(uint64_t window, double scale)',
  windowShow: 'int32_t tauri_window_show(uint64_t window)',
  windowHide: 'int32_t tauri_window_hide(uint64_t window)',
  windowCenter: 'int32_t tauri_window_center(uint64_t window)',
  windowMaximize: 'int32_t tauri_window_maximize(uint64_t window)',
  windowUnmaximize: 'int32_t tauri_window_unmaximize(uint64_t window)',
  windowMinimize: 'int32_t tauri_window_minimize(uint64_t window)',
  windowUnminimize: 'int32_t tauri_window_unminimize(uint64_t window)',
  windowClose: 'int32_t tauri_window_close(uint64_t window)',
  windowDestroy: 'int32_t tauri_window_destroy(uint64_t window)',
  windowEval: 'int32_t tauri_window_eval(uint64_t window, const char *js)',
  windowNavigate: 'int32_t tauri_window_navigate(uint64_t window, const char *url)',
  windowReload: 'int32_t tauri_window_reload(uint64_t window)'
}

/** Binds every declaration against a koffi library handle. */
export function declare(lib) {
  return Object.fromEntries(Object.entries(DECLS).map(([name, decl]) => [name, lib.func(decl)]))
}
