/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function run(args: Array<string>, binName: string | undefined | null, callback: (...args: any[]) => any): void
export declare function logError(error: string): void
