#!/bin/bash

mkdir -p {{app_name}}.AppDir
cp -r bundle/deb/{{bundle_name}}/data/usr {{app_name}}.AppDir
cp {{app_name}} {{app_name}}.AppDir/AppRun

cd {{app_name}}.AppDir

cp usr/share/icons/hicolor/256x265/apps/{{app_name}}.png {{app_name}}.png

echo '[Desktop Entry]' > {{app_name}}.desktop
echo 'Version=1.0' >> {{app_name}}.desktop
echo 'Comment=A Tauri App' >> {{app_name}}.desktop
echo 'Exec={{app_name}}' >> {{app_name}}.desktop
echo 'Icon={{app_name}}' >> {{app_name}}.desktop
echo 'Name={{app_name_uppercase}}' >> {{app_name}}.desktop
echo 'Terminal=false' >> {{app_name}}.desktop
echo 'Type=Application' >> {{app_name}}.desktop
echo 'Categories=X-Web;' >> {{app_name}}.desktop

cd ..

mksquashfs {{app_name}}.AppDir {{app_name}}.squashfs -root-owned -noappend
# cat runtime >> {{app_name}}.AppImage
cat {{app_name}}.squashfs >> {{app_name}}.AppImage
chmod a+x {{app_name}}.AppImage
