#!/bin/sh

# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

. "$(dirname "$0")/_/husky.sh"

if [ -z "$(git diff --name-only tooling/api)" ]; then
  echo "skipping api - no changes detected"
else
  cd tooling/api
  yarn format
  yarn lint-fix
  cd ../..
fi

if [ -z "$(git diff --name-only tooling/cli.js)" ]; then
  echo "skipping cli.js - no changes detected"
else
  cd tooling/cli.js
  yarn format
  yarn lint-fix
  cd ../..
fi

if [ -z "$(git diff --name-only tooling/create-tauri-app)" ]; then
  echo "skipping create-tauri-app - no changes detected"
else
  cd tooling/create-tauri-app
  yarn format
  yarn lint-fix
  cd ../..
fi
