#!/bin/sh

# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

. "$(dirname "$0")/_/husky.sh"

cd tooling/api
yarn format
yarn lint-fix
cd ../cli.js
yarn format
yarn lint-fix
