// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// Generated by bindings/bindgen/generate.mjs from crates/tauri-ffi/api-manifest.json — do not edit.
// 'buffer' string params expect null-terminated Uint8Arrays
// (new TextEncoder().encode(s + '\0')). Blocking calls are declared
// nonblocking so they run off Deno's main thread and resolve promises.

export const ABI_VERSION = 2

export const CODES = {
  OK: 0,
  GENERIC: -1,
  INVALID_HANDLE: -2,
  TIMEOUT: -3,
  CLOSED: -4,
  INVALID_ARG: -5,
  PANIC: -7,
  NOT_FOUND: -8
} as const

// Plain `as const` (no `satisfies`) so JSR's no-slow-types check accepts it;
// Deno.dlopen validates the interface shape at load time anyway.
export const SYMBOLS = {
  tauri_ffi_version: { parameters: [], result: 'pointer' },
  tauri_ffi_abi_version: { parameters: [], result: 'u32' },
  tauri_last_error_message: { parameters: [], result: 'pointer' },
  tauri_string_free: { parameters: ['pointer'], result: 'void' },
  tauri_handle_close: { parameters: ['u64'], result: 'i32' },
  tauri_app_builder_new: { parameters: ['buffer', 'buffer'], result: 'i32' },
  tauri_app_builder_set_assets_dir: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_builder_register_command: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_builder_add_capability: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_build: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_run: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_exit: { parameters: ['u64', 'i32'], result: 'i32' },
  tauri_events_next: { parameters: ['u64', 'u32', 'buffer'], result: 'i32', nonblocking: true },
  tauri_app_emit: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_app_emit_to: { parameters: ['u64', 'buffer', 'buffer', 'buffer'], result: 'i32' },
  tauri_app_listen: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_app_unlisten: { parameters: ['u64', 'u32'], result: 'i32' },
  tauri_invoke_resolve: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_invoke_reject: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_create: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32', nonblocking: true },
  tauri_app_get_window: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_app_window_labels: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_label: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_title: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_url: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_scale_factor: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_inner_size: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_window_outer_size: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_window_inner_position: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_window_outer_position: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_window_is_visible: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_focused: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_fullscreen: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_maximized: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_minimized: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_resizable: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_set_title: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_set_size: { parameters: ['u64', 'f64', 'f64', 'bool'], result: 'i32' },
  tauri_window_set_position: { parameters: ['u64', 'f64', 'f64', 'bool'], result: 'i32' },
  tauri_window_set_fullscreen: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_resizable: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_always_on_top: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_decorations: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_focus: { parameters: ['u64'], result: 'i32' },
  tauri_window_set_zoom: { parameters: ['u64', 'f64'], result: 'i32' },
  tauri_window_show: { parameters: ['u64'], result: 'i32' },
  tauri_window_hide: { parameters: ['u64'], result: 'i32' },
  tauri_window_center: { parameters: ['u64'], result: 'i32' },
  tauri_window_maximize: { parameters: ['u64'], result: 'i32' },
  tauri_window_unmaximize: { parameters: ['u64'], result: 'i32' },
  tauri_window_minimize: { parameters: ['u64'], result: 'i32' },
  tauri_window_unminimize: { parameters: ['u64'], result: 'i32' },
  tauri_window_close: { parameters: ['u64'], result: 'i32' },
  tauri_window_destroy: { parameters: ['u64'], result: 'i32' },
  tauri_window_eval: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_navigate: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_reload: { parameters: ['u64'], result: 'i32' }
} as const
