// Copyright 2019-2024 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// Generated by bindings/bindgen/generate.mjs from crates/tauri-ffi/api-manifest.json — do not edit.
// 'buffer' string params expect null-terminated Uint8Arrays
// (new TextEncoder().encode(s + '\0')). Blocking calls are declared
// nonblocking so they run off Deno's main thread and resolve promises.

export const ABI_VERSION = 10

export const CODES = {
  OK: 0,
  GENERIC: -1,
  INVALID_HANDLE: -2,
  TIMEOUT: -3,
  CLOSED: -4,
  INVALID_ARG: -5,
  UNSUPPORTED: -6,
  PANIC: -7,
  NOT_FOUND: -8
} as const

// Plain `as const` (no `satisfies`) so JSR's no-slow-types check accepts it;
// Deno.dlopen validates the interface shape at load time anyway.
export const SYMBOLS = {
  tauri_ffi_version: { parameters: [], result: 'pointer' },
  tauri_ffi_abi_version: { parameters: [], result: 'u32' },
  tauri_last_error_message: { parameters: [], result: 'pointer' },
  tauri_string_free: { parameters: ['pointer'], result: 'void' },
  tauri_handle_close: { parameters: ['u64'], result: 'i32' },
  tauri_app_builder_new: { parameters: ['buffer', 'buffer'], result: 'i32' },
  tauri_app_builder_set_assets_dir: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_set_assets_archive: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_set_assets_archive_bytes: {
    parameters: ['u64', 'buffer', 'u32'],
    result: 'i32'
  },
  tauri_app_builder_set_dev: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_app_builder_register_command: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_add_capability: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_register_uri_scheme_protocol: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_append_invoke_initialization_script: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_set_device_event_filter: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_set_macos_default_menu: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_app_builder_set_default_window_icon: {
    parameters: ['u64', 'buffer', 'u32', 'u32'],
    result: 'i32'
  },
  tauri_app_builder_set_default_window_icon_path: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_set_app_icon: {
    parameters: ['u64', 'buffer', 'u32'],
    result: 'i32'
  },
  tauri_app_builder_set_any_thread: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_app_builder_set_page_load_events: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_app_builder_set_webview_events: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_app_builder_enable_localhost: {
    parameters: ['u64', 'u32'],
    result: 'i32'
  },
  tauri_app_builder_enable_single_instance: {
    parameters: ['u64'],
    result: 'i32'
  },
  tauri_plugin_new: { parameters: ['buffer', 'buffer'], result: 'i32' },
  tauri_plugin_set_init_script: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_plugin_register_command: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_builder_add_plugin: { parameters: ['u64', 'u64'], result: 'i32' },
  tauri_app_build: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_run: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_exit: { parameters: ['u64', 'i32'], result: 'i32' },
  tauri_events_next: {
    parameters: ['u64', 'u32', 'buffer'],
    result: 'i32',
    nonblocking: true
  },
  tauri_app_emit: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_app_emit_to: {
    parameters: ['u64', 'buffer', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_app_listen: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_app_unlisten: { parameters: ['u64', 'u32'], result: 'i32' },
  tauri_invoke_resolve: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_invoke_reject: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_uri_scheme_respond: {
    parameters: ['u64', 'u32', 'buffer', 'buffer', 'u32'],
    result: 'i32'
  },
  tauri_webview_window_create: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32',
    nonblocking: true
  },
  tauri_app_get_webview_window: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_app_webview_window_labels: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_label: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_window_title: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_window_url: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_window_scale_factor: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_inner_size: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_outer_size: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_inner_position: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_outer_position: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_visible: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_focused: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_fullscreen: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_maximized: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_minimized: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_resizable: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_title: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_size: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_position: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_fullscreen: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_resizable: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_always_on_top: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_decorations: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_focus: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_set_zoom: { parameters: ['u64', 'f64'], result: 'i32' },
  tauri_webview_window_show: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_hide: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_center: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_maximize: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_unmaximize: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_minimize: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_unminimize: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_close: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_destroy: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_eval: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_window_navigate: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_reload: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_is_decorated: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_closable: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_maximizable: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_minimizable: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_always_on_top: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_enabled: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_menu_visible: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_is_devtools_open: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_theme: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_window_set_closable: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_maximizable: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_minimizable: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_always_on_bottom: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_content_protected: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_skip_taskbar: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_shadow: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_visible_on_all_workspaces: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_ignore_cursor_events: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_cursor_visible: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_cursor_grab: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_enabled: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_focusable: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_simple_fullscreen: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_min_size: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_max_size: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_cursor_position: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_webview_window_set_theme: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_cursor_icon: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_request_user_attention: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_progress_bar: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_effects: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_size_constraints: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_background_color: {
    parameters: ['u64', 'u32', 'u32', 'u32', 'u32'],
    result: 'i32'
  },
  tauri_webview_window_set_badge_count: {
    parameters: ['u64', 'i32'],
    result: 'i32'
  },
  tauri_webview_window_set_badge_label: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_title_bar_style: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_set_overlay_icon: {
    parameters: ['u64', 'buffer', 'u32', 'u32'],
    result: 'i32'
  },
  tauri_webview_window_ns_window: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_ns_view: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_hwnd: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_window_start_dragging: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_print: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_clear_all_browsing_data: {
    parameters: ['u64'],
    result: 'i32'
  },
  tauri_webview_window_hide_menu: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_show_menu: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_open_devtools: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_close_devtools: { parameters: ['u64'], result: 'i32' },
  tauri_webview_window_current_monitor: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_primary_monitor: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_available_monitors: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_monitor_from_point: {
    parameters: ['u64', 'f64', 'f64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_window_cursor_position: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_app_config: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_package_info: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_path: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_app_get_focused_window: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_add_capability: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_once: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_app_set_theme: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_cursor_position: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_app_request_restart: { parameters: ['u64'], result: 'i32' },
  tauri_app_set_activation_policy: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_app_set_dock_visibility: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_app_show: { parameters: ['u64'], result: 'i32' },
  tauri_app_hide: { parameters: ['u64'], result: 'i32' },
  tauri_tray_new: { parameters: ['u64', 'buffer', 'buffer'], result: 'i32' },
  tauri_tray_id: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_tray_set_icon: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_tray_set_icon_as_template: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_tray_set_tooltip: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_tray_set_title: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_tray_set_visible: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_tray_set_show_menu_on_left_click: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_app_remove_tray_by_id: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_create: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32',
    nonblocking: true
  },
  tauri_window_add_webview: {
    parameters: ['u64', 'buffer', 'f64', 'f64', 'f64', 'f64', 'bool', 'buffer'],
    result: 'i32',
    nonblocking: true
  },
  tauri_window_webviews: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_app_get_window: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_app_window_labels: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_label: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_title: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_theme: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_scale_factor: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_inner_size: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_window_outer_size: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_window_inner_position: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_window_outer_position: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_window_cursor_position: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_window_is_visible: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_focused: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_fullscreen: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_maximized: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_minimized: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_resizable: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_decorated: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_closable: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_maximizable: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_minimizable: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_always_on_top: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_is_enabled: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_is_menu_visible: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_set_fullscreen: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_resizable: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_always_on_top: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_decorations: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_closable: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_maximizable: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_minimizable: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_always_on_bottom: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_content_protected: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_skip_taskbar: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_shadow: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_visible_on_all_workspaces: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_ignore_cursor_events: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_cursor_visible: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_cursor_grab: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_enabled: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_focusable: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_window_set_simple_fullscreen: {
    parameters: ['u64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_focus: { parameters: ['u64'], result: 'i32' },
  tauri_window_show: { parameters: ['u64'], result: 'i32' },
  tauri_window_hide: { parameters: ['u64'], result: 'i32' },
  tauri_window_center: { parameters: ['u64'], result: 'i32' },
  tauri_window_maximize: { parameters: ['u64'], result: 'i32' },
  tauri_window_unmaximize: { parameters: ['u64'], result: 'i32' },
  tauri_window_minimize: { parameters: ['u64'], result: 'i32' },
  tauri_window_unminimize: { parameters: ['u64'], result: 'i32' },
  tauri_window_close: { parameters: ['u64'], result: 'i32' },
  tauri_window_destroy: { parameters: ['u64'], result: 'i32' },
  tauri_window_start_dragging: { parameters: ['u64'], result: 'i32' },
  tauri_window_hide_menu: { parameters: ['u64'], result: 'i32' },
  tauri_window_show_menu: { parameters: ['u64'], result: 'i32' },
  tauri_window_set_title: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_set_size: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_position: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_min_size: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_max_size: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_cursor_position: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_window_set_theme: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_set_cursor_icon: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_request_user_attention: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_set_progress_bar: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_set_effects: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_set_size_constraints: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_set_background_color: {
    parameters: ['u64', 'u32', 'u32', 'u32', 'u32'],
    result: 'i32'
  },
  tauri_window_set_badge_count: { parameters: ['u64', 'i32'], result: 'i32' },
  tauri_window_set_badge_label: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_set_title_bar_style: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_set_overlay_icon: {
    parameters: ['u64', 'buffer', 'u32', 'u32'],
    result: 'i32'
  },
  tauri_window_ns_window: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_ns_view: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_hwnd: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_window_current_monitor: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_primary_monitor: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_available_monitors: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_window_monitor_from_point: {
    parameters: ['u64', 'f64', 'f64', 'buffer'],
    result: 'i32'
  },
  tauri_webview_label: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_url: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_position: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_webview_size: {
    parameters: ['u64', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_webview_get_window: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_reload: { parameters: ['u64'], result: 'i32' },
  tauri_webview_print: { parameters: ['u64'], result: 'i32' },
  tauri_webview_set_focus: { parameters: ['u64'], result: 'i32' },
  tauri_webview_show: { parameters: ['u64'], result: 'i32' },
  tauri_webview_hide: { parameters: ['u64'], result: 'i32' },
  tauri_webview_close: { parameters: ['u64'], result: 'i32' },
  tauri_webview_clear_all_browsing_data: { parameters: ['u64'], result: 'i32' },
  tauri_webview_eval: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_navigate: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_webview_set_zoom: { parameters: ['u64', 'f64'], result: 'i32' },
  tauri_webview_set_auto_resize: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_webview_set_size: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_webview_set_position: {
    parameters: ['u64', 'f64', 'f64', 'bool'],
    result: 'i32'
  },
  tauri_webview_set_background_color: {
    parameters: ['u64', 'u32', 'u32', 'u32', 'u32'],
    result: 'i32'
  },
  tauri_webview_reparent: { parameters: ['u64', 'u64'], result: 'i32' },
  tauri_webview_open_devtools: { parameters: ['u64'], result: 'i32' },
  tauri_webview_close_devtools: { parameters: ['u64'], result: 'i32' },
  tauri_webview_is_devtools_open: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  },
  tauri_menu_new: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_menu_item_new: {
    parameters: ['u64', 'buffer', 'buffer', 'bool', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_menu_check_item_new: {
    parameters: ['u64', 'buffer', 'buffer', 'bool', 'bool', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_menu_predefined_item_new: {
    parameters: ['u64', 'buffer', 'buffer', 'buffer'],
    result: 'i32'
  },
  tauri_submenu_new: {
    parameters: ['u64', 'buffer', 'buffer', 'bool', 'buffer'],
    result: 'i32'
  },
  tauri_menu_append: { parameters: ['u64', 'u64'], result: 'i32' },
  tauri_submenu_append: { parameters: ['u64', 'u64'], result: 'i32' },
  tauri_menu_set_as_app_menu: { parameters: ['u64'], result: 'i32' },
  tauri_menu_set_as_window_menu: { parameters: ['u64', 'u64'], result: 'i32' },
  tauri_tray_set_menu: { parameters: ['u64', 'u64'], result: 'i32' },
  tauri_menu_item_id: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_menu_item_set_text: { parameters: ['u64', 'buffer'], result: 'i32' },
  tauri_menu_item_set_enabled: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_menu_item_set_checked: { parameters: ['u64', 'bool'], result: 'i32' },
  tauri_menu_item_set_accelerator: {
    parameters: ['u64', 'buffer'],
    result: 'i32'
  }
} as const
