# Copyright 2019-2024 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: publish `@tauri-apps/cli`
env:
  DEBUG: napi:*
  APP_NAME: cli
  MACOSX_DEPLOYMENT_TARGET: '10.13'
on:
  pull_request:

defaults:
  run:
    working-directory: packages/cli/

# permissions:
#   contents: write # update release
#   id-token: write # oidc token

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: pnpm build --target=x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
            build: pnpm build --target=aarch64-apple-darwin

          - host: windows-latest
            build: pnpm build --target=x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            build: pnpm build --target=i686-pc-windows-msvc
            target: i686-pc-windows-msvc
          - host: windows-latest
            target: aarch64-pc-windows-msvc
            build: pnpm build --target=aarch64-pc-windows-msvc

          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: pnpm build --target=x86_64-unknown-linux-gnu --cross-compile
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: pnpm build --target=x86_64-unknown-linux-musl --cross-compile
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: pnpm build --target=aarch64-unknown-linux-gnu --cross-compile
            setup: |
              sudo apt-get update
              sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu -y
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build: pnpm build --target=armv7-unknown-linux-gnueabihf --cross-compile
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: pnpm build --target=aarch64-unknown-linux-musl --cross-compile
          - host: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu
            build: pnpm build --target=riscv64gc-unknown-linux-gnu --cross-compile
            setup: |
              sudo apt-get update
              sudo apt-get install gcc-riscv64-linux-gnu g++-riscv64-linux-gnu -y
    name: stable - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v7
      - run: npm i -g --force corepack
      - name: Setup node
        uses: actions/setup-node@v6
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.settings.target }}

      - uses: mlugg/setup-zig@v2
        if: ${{ contains(matrix.settings.target, 'musl') }}
        with:
          version: 0.14.1
      - name: Install cargo-zigbuild
        uses: taiki-e/install-action@v2
        if: ${{ contains(matrix.settings.target, 'musl') }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tool: cargo-zigbuild

      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: bindings-${{ matrix.settings.target }}
          path: packages/cli/${{ env.APP_NAME }}.*.node
          if-no-files-found: error
  #  build-freebsd:
  #    runs-on: macos-10.15
  #    name: Build FreeBSD
  #    steps:
  #      - uses: actions/checkout@v7
  #      - name: Build
  #        id: build
  #        uses: vmactions/freebsd-vm@v0.1.6
  #        env:
  #          DEBUG: napi:*
  #          RUSTUP_HOME: /usr/local/rustup
  #          CARGO_HOME: /usr/local/cargo
  #          RUSTUP_IO_THREADS: 1
  #        with:
  #          envs: DEBUG RUSTUP_HOME CARGO_HOME RUSTUP_IO_THREADS
  #          usesh: true
  #          mem: 3000
  #          prepare: |
  #            pkg install -y curl node14 python2
  #            curl -qL https://www.npmjs.com/install.sh | sh
  #            npm install -g pnpm
  #            curl https://sh.rustup.rs -sSf --output rustup.sh
  #            sh rustup.sh -y --profile minimal --default-toolchain stable
  #            export PATH="/usr/local/cargo/bin:$PATH"
  #            echo "~~~~ rustc --version ~~~~"
  #            rustc --version
  #            echo "~~~~ node -v ~~~~"
  #            node -v
  #            echo "~~~~ pnpm --version ~~~~"
  #            pnpm --version
  #          run: |
  #            export PATH="/usr/local/cargo/bin:$PATH"
  #            pwd
  #            ls -lah
  #            whoami
  #            env
  #            freebsd-version
  #            cd ./packages/cli/
  #            pnpm i --frozen-lockfile --ignore-scripts
  #            pnpm build
  #            strip -x *.node
  #            rm -rf node_modules
  #            rm -rf ../../target
  #      - name: Upload artifact
  #        uses: actions/upload-artifact@v4
  #        with:
  #          name: bindings-freebsd
  #          path: packages/cli/${{ env.APP_NAME }}.*.node
  #          if-no-files-found: error
  test-macOS-windows-binding:
    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
            architecture: arm64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            architecture: x64
          - host: windows-11-arm
            target: aarch64-pc-windows-msvc
            architecture: arm64
          - host: macos-latest
            target: x86_64-apple-darwin
            architecture: x64
        node:
          - '20'
          - '22'
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v7
      - run: npm i -g --force corepack
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          architecture: ${{ matrix.settings.architecture }}
      - name: Install dependencies
        run: pnpm install
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: bindings-${{ matrix.settings.target }}
          path: 'packages/cli/'
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Test bindings
        run: pnpm test
  test-linux-binding:
    name: Test ${{ matrix.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
        node:
          - '20'
          - '22'
        exclude:
          - target: armv7-unknown-linux-gnueabihf
            node: '24'
    runs-on: ${{ contains(matrix.target, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v7
      - run: npm i -g --force corepack
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Output docker params
        id: docker
        run: |
          node -e "
            if ('${{ matrix.target }}'.startsWith('aarch64')) {
              console.log('PLATFORM=linux/arm64')
            } else if ('${{ matrix.target }}'.startsWith('armv7')) {
              console.log('PLATFORM=linux/arm/v7')
            } else {
              console.log('PLATFORM=linux/amd64')
            }
          " >> $GITHUB_OUTPUT
          node -e "
            if ('${{ matrix.target }}'.endsWith('-musl')) {
              console.log('IMAGE=node:${{ matrix.node }}-alpine')
            } else {
              console.log('IMAGE=node:${{ matrix.node }}-slim')
            }
          " >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: |
          pnpm config set --json supportedArchitectures.cpu '["current", "arm64", "x64", "arm"]'
          pnpm config set --json supportedArchitectures.libc '["current", "musl", "gnu"]'
          pnpm install
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: bindings-${{ matrix.target }}
          path: 'packages/cli/'
      - name: List packages
        run: ls -R .
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        if: ${{ contains(matrix.target, 'armv7') }}
        with:
          platforms: all
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: ${{ contains(matrix.target, 'armv7') }}
      - name: Test bindings
        uses: tj-actions/docker-run@v2
        with:
          image: ${{ steps.docker.outputs.IMAGE }}
          name: test-bindings-${{ matrix.target }}
          options: -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }} --platform ${{ steps.docker.outputs.PLATFORM }}
          args: pnpm test
  # publish:
  #   name: Publish
  #   runs-on: ubuntu-latest
  #   needs:
  #     #- build-freebsd
  #     - test-macOS-windows-binding
  #     - test-linux-binding
  #   steps:
  #     - uses: actions/checkout@v7
  #     - run: npm i -g --force corepack
  #     - name: Setup node
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 24
  #         cache: 'pnpm'
  #     - name: Install dependencies
  #       run: pnpm i --frozen-lockfile --ignore-scripts
  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v8
  #       with:
  #         path: packages/cli/artifacts
  #     - name: Move artifacts
  #       run: pnpm artifacts
  #     - name: List packages
  #       run: ls -R ./npm
  #       shell: bash
  #     - name: Publish
  #       run: |
  #         npm publish
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NODE_AUTH_TOKEN: ''
  #         RELEASE_ID: ${{ github.event.client_payload.releaseId || inputs.releaseId }}
